WITH COVERAGE1 AS
  (SELECT * FROM DB2TAB.LH_COV_PHA C1 WHERE C1.COV_PHA_NBR = 1)
, ALL_BASE_COVS AS (
  SELECT TEMPCOV1.CK_SYS_CD, TEMPCOV1.TCH_POL_ID, TEMPCOV1.CK_CMP_CD
    , TEMPCOVALL.COV_PHA_NBR
    , ROUND(REAL(TEMPCOVALL.COV_UNT_QTY) * REAL(TEMPCOVALL.COV_VPU_AMT), 2) SPECAMT
    , ROUND(REAL(TEMPCOVALL.OGN_SPC_UNT_QTY) * REAL(TEMPCOVALL.COV_VPU_AMT), 2) ORIGSPECAMT
  FROM DB2TAB.LH_COV_PHA TEMPCOV1
    INNER JOIN DB2TAB.LH_COV_PHA TEMPCOVALL
      ON TEMPCOV1.COV_PHA_NBR = 1
      AND TEMPCOV1.CK_SYS_CD = TEMPCOVALL.CK_SYS_CD
      AND TEMPCOV1.CK_CMP_CD = TEMPCOVALL.CK_CMP_CD
      AND TEMPCOV1.TCH_POL_ID = TEMPCOVALL.TCH_POL_ID
      AND (TEMPCOVALL.PLN_DES_SER_CD = TEMPCOV1.PLN_DES_SER_CD))
, COVSUMMARY AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID
    , SUM(ALL_BASE_COVS.SPECAMT) TOTAL_SA
    , SUM(ALL_BASE_COVS.ORIGSPECAMT) TOTAL_ORIGINAL_SA
  FROM ALL_BASE_COVS
  GROUP BY CK_SYS_CD, CK_CMP_CD, TCH_POL_ID)
, LASTMV AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, MAX(MVRY_DT) LASTMVDT
  FROM DB2TAB.LH_POL_MVRY_VAL
  GROUP BY CK_SYS_CD, CK_CMP_CD, TCH_POL_ID)
, MVVAL AS (
  SELECT MV.CK_SYS_CD, MV.CK_CMP_CD, MV.TCH_POL_ID, MV.CSV_AMT
    , LASTMV.LASTMVDT
    , ROUND(REAL(MV.CSV_AMT) * REAL(ADVPROD.CDR_PCT)/100, 2) DB
    , CASE ADVPROD.DTH_BNF_PLN_OPT_CD
        WHEN '1' THEN 0
        WHEN '2' THEN REAL(MV.CSV_AMT)
        WHEN '3' THEN (TEMPPOLTOTALS.TOT_REG_PRM_AMT + TEMPPOLTOTALS.TOT_ADD_PRM_AMT)
        ELSE 0 END OPTDB
    , (TEMPPOLTOTALS.TOT_REG_PRM_AMT + TEMPPOLTOTALS.TOT_ADD_PRM_AMT) TOTALPREM
  FROM DB2TAB.LH_POL_MVRY_VAL MV
    INNER JOIN LASTMV ON MV.CK_SYS_CD = LASTMV.CK_SYS_CD
      AND MV.CK_CMP_CD = LASTMV.CK_CMP_CD
      AND MV.TCH_POL_ID = LASTMV.TCH_POL_ID
      AND MV.MVRY_DT = LASTMV.LASTMVDT
    INNER JOIN DB2TAB.LH_NON_TRD_POL ADVPROD
      ON MV.CK_SYS_CD = ADVPROD.CK_SYS_CD
      AND MV.CK_CMP_CD = ADVPROD.CK_CMP_CD
      AND MV.TCH_POL_ID = ADVPROD.TCH_POL_ID
    INNER JOIN DB2TAB.LH_POL_TOTALS TEMPPOLTOTALS
      ON MV.CK_SYS_CD = TEMPPOLTOTALS.CK_SYS_CD
      AND MV.CK_CMP_CD = TEMPPOLTOTALS.CK_CMP_CD
      AND MV.TCH_POL_ID = TEMPPOLTOTALS.TCH_POL_ID)
, GLP AS (
  SELECT DISTINCT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID,
    TEMPGLP.GDL_PRM_AMT GLP_VALUE
  FROM DB2TAB.LH_COV_INS_GDL_PRM TEMPGLP
  WHERE TEMPGLP.COV_PHA_NBR = 1
    AND TEMPGLP.PRM_RT_TYP_CD = 'A')
, GSP AS (
  SELECT DISTINCT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID,
    TEMPGSP.GDL_PRM_AMT GSP_VALUE
  FROM DB2TAB.LH_COV_INS_GDL_PRM TEMPGSP
  WHERE TEMPGSP.COV_PHA_NBR = 1
    AND TEMPGSP.PRM_RT_TYP_CD = 'S')

SELECT DISTINCT
  CURRENT_DATE RunDate
  , POLICY1.CK_POLICY_NBR PolicyNumber
  , POLICY1.CK_CMP_CD CompanyCode
  , POLICY1.PRM_PAY_STA_REA_CD StatusCode
  , POLICY1.SUS_CD SuspenseCode
  , SUBSTR(POLICY1.SVC_AGC_NBR, 1, 1) AgentCode
  , CASE WHEN POLICY1.POL_ISS_ST_CD = '01' THEN 'AL'
    WHEN POLICY1.POL_ISS_ST_CD = '02' THEN 'AZ'
    WHEN POLICY1.POL_ISS_ST_CD = '03' THEN 'AR'
    WHEN POLICY1.POL_ISS_ST_CD = '04' THEN 'CA'
    WHEN POLICY1.POL_ISS_ST_CD = '05' THEN 'CO'
    WHEN POLICY1.POL_ISS_ST_CD = '06' THEN 'CT'
    WHEN POLICY1.POL_ISS_ST_CD = '07' THEN 'DE'
    WHEN POLICY1.POL_ISS_ST_CD = '08' THEN 'DC'
    WHEN POLICY1.POL_ISS_ST_CD = '09' THEN 'FL'
    WHEN POLICY1.POL_ISS_ST_CD = '10' THEN 'GA'
    WHEN POLICY1.POL_ISS_ST_CD = '11' THEN 'ID'
    WHEN POLICY1.POL_ISS_ST_CD = '12' THEN 'IL'
    WHEN POLICY1.POL_ISS_ST_CD = '13' THEN 'IN'
    WHEN POLICY1.POL_ISS_ST_CD = '14' THEN 'IA'
    WHEN POLICY1.POL_ISS_ST_CD = '15' THEN 'KS'
    WHEN POLICY1.POL_ISS_ST_CD = '16' THEN 'KY'
    WHEN POLICY1.POL_ISS_ST_CD = '17' THEN 'LA'
    WHEN POLICY1.POL_ISS_ST_CD = '18' THEN 'ME'
    WHEN POLICY1.POL_ISS_ST_CD = '19' THEN 'MD'
    WHEN POLICY1.POL_ISS_ST_CD = '20' THEN 'MA'
    WHEN POLICY1.POL_ISS_ST_CD = '21' THEN 'MI'
    WHEN POLICY1.POL_ISS_ST_CD = '22' THEN 'MN'
    WHEN POLICY1.POL_ISS_ST_CD = '23' THEN 'MS'
    WHEN POLICY1.POL_ISS_ST_CD = '24' THEN 'MO'
    WHEN POLICY1.POL_ISS_ST_CD = '25' THEN 'MT'
    WHEN POLICY1.POL_ISS_ST_CD = '26' THEN 'NE'
    WHEN POLICY1.POL_ISS_ST_CD = '27' THEN 'NV'
    WHEN POLICY1.POL_ISS_ST_CD = '28' THEN 'NH'
    WHEN POLICY1.POL_ISS_ST_CD = '29' THEN 'NJ'
    WHEN POLICY1.POL_ISS_ST_CD = '30' THEN 'NM'
    WHEN POLICY1.POL_ISS_ST_CD = '31' THEN 'NY'
    WHEN POLICY1.POL_ISS_ST_CD = '32' THEN 'NC'
    WHEN POLICY1.POL_ISS_ST_CD = '33' THEN 'ND'
    WHEN POLICY1.POL_ISS_ST_CD = '34' THEN 'OH'
    WHEN POLICY1.POL_ISS_ST_CD = '35' THEN 'OK'
    WHEN POLICY1.POL_ISS_ST_CD = '36' THEN 'OR'
    WHEN POLICY1.POL_ISS_ST_CD = '37' THEN 'PA'
    WHEN POLICY1.POL_ISS_ST_CD = '38' THEN 'RI'
    WHEN POLICY1.POL_ISS_ST_CD = '39' THEN 'SC'
    WHEN POLICY1.POL_ISS_ST_CD = '40' THEN 'SD'
    WHEN POLICY1.POL_ISS_ST_CD = '41' THEN 'TN'
    WHEN POLICY1.POL_ISS_ST_CD = '42' THEN 'TX'
    WHEN POLICY1.POL_ISS_ST_CD = '43' THEN 'UT'
    WHEN POLICY1.POL_ISS_ST_CD = '44' THEN 'VT'
    WHEN POLICY1.POL_ISS_ST_CD = '45' THEN 'VA'
    WHEN POLICY1.POL_ISS_ST_CD = '46' THEN 'WA'
    WHEN POLICY1.POL_ISS_ST_CD = '47' THEN 'WV'
    WHEN POLICY1.POL_ISS_ST_CD = '48' THEN 'WI'
    WHEN POLICY1.POL_ISS_ST_CD = '49' THEN 'WY'
    WHEN POLICY1.POL_ISS_ST_CD = '50' THEN 'AK'
    WHEN POLICY1.POL_ISS_ST_CD = '51' THEN 'HI'
    WHEN POLICY1.POL_ISS_ST_CD = '52' THEN 'PR'
    ELSE POLICY1.POL_ISS_ST_CD END IssueState
  , COVERAGE1.PLN_DES_SER_CD Plancode
  , COVERAGE1.POL_FRM_NBR FormNumber
  , VARCHAR_FORMAT(COVERAGE1.ISSUE_DT, 'MM/DD/YYYY') IssueDt
  , COVERAGE1.INS_ISS_AGE IssueAge
  , USERGEN.FUZGREIN_IND RGA_Ind
  , GSP.GSP_VALUE
  , GLP.GLP_VALUE
FROM DB2TAB.LH_BAS_POL POLICY1
  INNER JOIN COVERAGE1
    ON POLICY1.CK_SYS_CD = COVERAGE1.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = COVERAGE1.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = COVERAGE1.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.TH_USER_GENERIC USERGEN
    ON POLICY1.CK_SYS_CD = USERGEN.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = USERGEN.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = USERGEN.TCH_POL_ID
  LEFT OUTER JOIN COVSUMMARY
    ON COVSUMMARY.CK_SYS_CD = POLICY1.CK_SYS_CD
    AND COVSUMMARY.CK_CMP_CD = POLICY1.CK_CMP_CD
    AND COVSUMMARY.TCH_POL_ID = POLICY1.TCH_POL_ID
  LEFT OUTER JOIN MVVAL
    ON POLICY1.CK_SYS_CD = MVVAL.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = MVVAL.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = MVVAL.TCH_POL_ID
  INNER JOIN GLP
    ON POLICY1.CK_SYS_CD = GLP.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = GLP.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = GLP.TCH_POL_ID
  INNER JOIN GSP
    ON POLICY1.CK_SYS_CD = GSP.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = GSP.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = GSP.TCH_POL_ID
WHERE POLICY1.CK_SYS_CD = 'I'
  AND (MVVAL.DB > COVSUMMARY.TOTAL_SA + MVVAL.OPTDB)
  AND (MVVAL.CSV_AMT >= MVVAL.TOTALPREM)
  AND GLP.GLP_VALUE >= 0.0
  AND GSP.GSP_VALUE <= 500.0
FETCH FIRST 25 ROWS ONLY