WITH COVERAGE1 AS
  (SELECT * FROM DB2TAB.LH_COV_PHA C1 WHERE C1.COV_PHA_NBR = 1)
, ALL_LOANS AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, PRF_LN_IND, LN_PRI_AMT,
    (CASE LN_ITS_AMT_TYP_CD WHEN '2' THEN POL_LN_ITS_AMT ELSE 0 END) LN_INT
  FROM DB2TAB.LH_FND_VAL_LOAN WHERE MVRY_DT = '9999-12-31'
  UNION
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, PRF_LN_IND, LN_PRI_AMT,
    (CASE LN_ITS_AMT_TYP_CD WHEN '2' THEN POL_LN_ITS_AMT ELSE 0 END) LN_INT
  FROM DB2TAB.LH_CSH_VAL_LOAN WHERE MVRY_DT = '9999-12-31')
, POLICYDEBT AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID,
    SUM(ALL_LOANS.LN_PRI_AMT) LOAN_PRINCIPLE,
    SUM(ALL_LOANS.LN_INT) LOAN_ACCRUED,
    SUM(CASE WHEN COALESCE(ALL_LOANS.PRF_LN_IND, '0') <> '1'
      THEN ALL_LOANS.LN_PRI_AMT ELSE 0 END) REG_LOAN_PRINCIPLE,
    SUM(CASE WHEN COALESCE(ALL_LOANS.PRF_LN_IND, '0') <> '1'
      THEN ALL_LOANS.LN_INT ELSE 0 END) REG_LOAN_ACCRUED,
    SUM(CASE WHEN ALL_LOANS.PRF_LN_IND = '1'
      THEN ALL_LOANS.LN_PRI_AMT ELSE 0 END) PREF_LOAN_PRINCIPLE,
    SUM(CASE WHEN ALL_LOANS.PRF_LN_IND = '1'
      THEN ALL_LOANS.LN_INT ELSE 0 END) PREF_LOAN_ACCRUED
  FROM ALL_LOANS
  GROUP BY CK_SYS_CD, CK_CMP_CD, TCH_POL_ID)
, CHANGE_SEGMENT AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, '9' AS CHG_TYP_CD FROM DB2TAB.LH_COV_TMN
  UNION
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, CHG_TYP_CD FROM DB2TAB.LH_NT_COV_CHG
  UNION
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, CHG_TYP_CD FROM DB2TAB.LH_NT_COV_CHG_SCH
  UNION
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, CHG_TYP_CD FROM DB2TAB.LH_SPM_BNF_CHG_SCH)
, ALL_BASE_COVS AS (
  SELECT TEMPCOV1.CK_SYS_CD, TEMPCOV1.TCH_POL_ID, TEMPCOV1.CK_CMP_CD
    , TEMPCOVALL.COV_PHA_NBR
    , ROUND(REAL(TEMPCOVALL.COV_UNT_QTY) * REAL(TEMPCOVALL.COV_VPU_AMT), 2) SPECAMT
    , ROUND(REAL(TEMPCOVALL.OGN_SPC_UNT_QTY) * REAL(TEMPCOVALL.COV_VPU_AMT), 2) ORIGSPECAMT
    , ROUND(REAL(TEMPCOVALL.LOW_DUR_1_CSV_AMT) * REAL(TEMPCOVALL.COV_UNT_QTY), 2) CV1
    , ROUND(REAL(TEMPCOVALL.LOW_DUR_2_CSV_AMT) * REAL(TEMPCOVALL.COV_UNT_QTY), 2) CV2
  FROM DB2TAB.LH_COV_PHA TEMPCOV1
    INNER JOIN DB2TAB.LH_COV_PHA TEMPCOVALL
      ON TEMPCOV1.COV_PHA_NBR = 1
      AND TEMPCOV1.CK_SYS_CD = TEMPCOVALL.CK_SYS_CD
      AND TEMPCOV1.CK_CMP_CD = TEMPCOVALL.CK_CMP_CD
      AND TEMPCOV1.TCH_POL_ID = TEMPCOVALL.TCH_POL_ID
      AND (TEMPCOVALL.PLN_DES_SER_CD = TEMPCOV1.PLN_DES_SER_CD OR TEMPCOVALL.PLN_DES_SER_CD = '1U144A00'))
, COVSUMMARY AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID
    , SUM(ALL_BASE_COVS.SPECAMT) TOTAL_SA
    , SUM(ALL_BASE_COVS.ORIGSPECAMT) TOTAL_ORIGINAL_SA
    , COUNT(ALL_BASE_COVS.COV_PHA_NBR) BASECOVCOUNT
    , SUM(ALL_BASE_COVS.CV1) TOTAL_CV1
    , SUM(ALL_BASE_COVS.CV2) TOTAL_CV2
  FROM ALL_BASE_COVS
  GROUP BY CK_SYS_CD, CK_CMP_CD, TCH_POL_ID)
, PREMWD_FACE AS (
  SELECT TEMPCOV1.CK_SYS_CD, TEMPCOV1.CK_CMP_CD, TEMPCOV1.TCH_POL_ID
    , SUM(ROUND(REAL(TEMPCOVALL.COV_UNT_QTY) * REAL(TEMPCOVALL.COV_VPU_AMT), 2)) TOTAL_FACE
  FROM DB2TAB.LH_COV_PHA TEMPCOV1
    INNER JOIN DB2TAB.LH_COV_PHA TEMPCOVALL
      ON TEMPCOV1.COV_PHA_NBR = 1
      AND TEMPCOV1.CK_SYS_CD = TEMPCOVALL.CK_SYS_CD
      AND TEMPCOV1.CK_CMP_CD = TEMPCOVALL.CK_CMP_CD
      AND TEMPCOV1.TCH_POL_ID = TEMPCOVALL.TCH_POL_ID
      AND (TEMPCOVALL.PLN_DES_SER_CD = TEMPCOV1.PLN_DES_SER_CD
           OR TEMPCOVALL.PLN_DES_SER_CD = '1U144A00')
  WHERE (TEMPCOVALL.NXT_CHG_TYP_CD <> '0'
         OR (TEMPCOVALL.NXT_CHG_DT IS NOT NULL
             AND TEMPCOVALL.NXT_CHG_DT > CURRENT DATE))
  GROUP BY TEMPCOV1.CK_SYS_CD, TEMPCOV1.CK_CMP_CD, TEMPCOV1.TCH_POL_ID)
, LASTMV AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, MAX(MVRY_DT) LASTMVDT
  FROM DB2TAB.LH_POL_MVRY_VAL
  GROUP BY CK_SYS_CD, CK_CMP_CD, TCH_POL_ID)
, MVVAL AS (
  SELECT MV.CK_SYS_CD, MV.CK_CMP_CD, MV.TCH_POL_ID, MV.CSV_AMT
    , LASTMV.LASTMVDT
    , ROUND(REAL(MV.CSV_AMT) * REAL(ADVPROD.CDR_PCT)/100, 2) DB
    , CASE ADVPROD.DTH_BNF_PLN_OPT_CD
        WHEN '1' THEN 0
        WHEN '2' THEN REAL(MV.CSV_AMT)
        WHEN '3' THEN (TEMPPOLTOTALS.TOT_REG_PRM_AMT + TEMPPOLTOTALS.TOT_ADD_PRM_AMT)
        ELSE 0 END OPTDB
    , (TEMPPOLTOTALS.TOT_REG_PRM_AMT + TEMPPOLTOTALS.TOT_ADD_PRM_AMT) TOTALPREM
  FROM DB2TAB.LH_POL_MVRY_VAL MV
    INNER JOIN LASTMV ON MV.CK_SYS_CD = LASTMV.CK_SYS_CD
      AND MV.CK_CMP_CD = LASTMV.CK_CMP_CD
      AND MV.TCH_POL_ID = LASTMV.TCH_POL_ID
      AND MV.MVRY_DT = LASTMV.LASTMVDT
    INNER JOIN DB2TAB.LH_NON_TRD_POL ADVPROD
      ON MV.CK_SYS_CD = ADVPROD.CK_SYS_CD
      AND MV.CK_CMP_CD = ADVPROD.CK_CMP_CD
      AND MV.TCH_POL_ID = ADVPROD.TCH_POL_ID
    INNER JOIN DB2TAB.LH_POL_TOTALS TEMPPOLTOTALS
      ON MV.CK_SYS_CD = TEMPPOLTOTALS.CK_SYS_CD
      AND MV.CK_CMP_CD = TEMPPOLTOTALS.CK_CMP_CD
      AND MV.TCH_POL_ID = TEMPPOLTOTALS.TCH_POL_ID)
, INTERPOLATION_MONTHS AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID
    , REAL(12 - MONTHS_BETWEEN(BASPOL.NXT_MVRY_PRC_DT, BASPOL.LST_ANV_DT)) MONTHS_TO_NEXT_ANN
    , REAL(MONTHS_BETWEEN(BASPOL.NXT_MVRY_PRC_DT, BASPOL.LST_ANV_DT)) MONTHS_YTD
  FROM DB2TAB.LH_BAS_POL BASPOL)
, ISWL_INTERPOLATED_GCV AS (
  SELECT COVSUMMARY.CK_SYS_CD, COVSUMMARY.CK_CMP_CD, COVSUMMARY.TCH_POL_ID
    , ROUND((INTERPOLATION_MONTHS.MONTHS_TO_NEXT_ANN * COVSUMMARY.TOTAL_CV1
            + INTERPOLATION_MONTHS.MONTHS_YTD * COVSUMMARY.TOTAL_CV2)/12, 2) ISWL_GCV
  FROM COVSUMMARY
    INNER JOIN INTERPOLATION_MONTHS
      ON COVSUMMARY.CK_SYS_CD = INTERPOLATION_MONTHS.CK_SYS_CD
      AND COVSUMMARY.CK_CMP_CD = INTERPOLATION_MONTHS.CK_CMP_CD
      AND COVSUMMARY.TCH_POL_ID = INTERPOLATION_MONTHS.TCH_POL_ID)
, GLP AS (
  SELECT DISTINCT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID,
    TEMPGLP.GDL_PRM_AMT GLP_VALUE
  FROM DB2TAB.LH_COV_INS_GDL_PRM TEMPGLP
  WHERE TEMPGLP.COV_PHA_NBR = 1
    AND TEMPGLP.PRM_RT_TYP_CD = 'A')
, FUND_VALUES AS (
  SELECT CK_CMP_CD, CK_SYS_CD, TCH_POL_ID, FND_ID_CD,
    SUM(CSV_AMT) FUNDAMT
  FROM DB2TAB.LH_POL_FND_VAL_TOT
  WHERE MVRY_DT = '9999-12-31'
  GROUP BY CK_CMP_CD, CK_SYS_CD, TCH_POL_ID, FND_ID_CD)

SELECT DISTINCT
  CURRENT_DATE RunDate
  , POLICY1.CK_POLICY_NBR PolicyNumber
  , RESULTCOV.COV_PHA_NBR CovPhase
  , POLICY1.CK_CMP_CD CompanyCode
  , RESULTCOV.PRD_LIN_TYP_CD ProductLineCode
  , POLICY1.PRM_PAY_STA_REA_CD StatusCode
  , POLICY1.SUS_CD SuspenseCode
  , SUBSTR(POLICY1.SVC_AGC_NBR, 1, 1) AgentCode
  , CASE WHEN POLICY1.POL_ISS_ST_CD = '01' THEN 'AL'
    WHEN POLICY1.POL_ISS_ST_CD = '02' THEN 'AZ'
    WHEN POLICY1.POL_ISS_ST_CD = '03' THEN 'AR'
    WHEN POLICY1.POL_ISS_ST_CD = '04' THEN 'CA'
    WHEN POLICY1.POL_ISS_ST_CD = '05' THEN 'CO'
    WHEN POLICY1.POL_ISS_ST_CD = '06' THEN 'CT'
    WHEN POLICY1.POL_ISS_ST_CD = '07' THEN 'DE'
    WHEN POLICY1.POL_ISS_ST_CD = '08' THEN 'DC'
    WHEN POLICY1.POL_ISS_ST_CD = '09' THEN 'FL'
    WHEN POLICY1.POL_ISS_ST_CD = '10' THEN 'GA'
    WHEN POLICY1.POL_ISS_ST_CD = '11' THEN 'ID'
    WHEN POLICY1.POL_ISS_ST_CD = '12' THEN 'IL'
    WHEN POLICY1.POL_ISS_ST_CD = '13' THEN 'IN'
    WHEN POLICY1.POL_ISS_ST_CD = '14' THEN 'IA'
    WHEN POLICY1.POL_ISS_ST_CD = '15' THEN 'KS'
    WHEN POLICY1.POL_ISS_ST_CD = '16' THEN 'KY'
    WHEN POLICY1.POL_ISS_ST_CD = '17' THEN 'LA'
    WHEN POLICY1.POL_ISS_ST_CD = '18' THEN 'ME'
    WHEN POLICY1.POL_ISS_ST_CD = '19' THEN 'MD'
    WHEN POLICY1.POL_ISS_ST_CD = '20' THEN 'MA'
    WHEN POLICY1.POL_ISS_ST_CD = '21' THEN 'MI'
    WHEN POLICY1.POL_ISS_ST_CD = '22' THEN 'MN'
    WHEN POLICY1.POL_ISS_ST_CD = '23' THEN 'MS'
    WHEN POLICY1.POL_ISS_ST_CD = '24' THEN 'MO'
    WHEN POLICY1.POL_ISS_ST_CD = '25' THEN 'MT'
    WHEN POLICY1.POL_ISS_ST_CD = '26' THEN 'NE'
    WHEN POLICY1.POL_ISS_ST_CD = '27' THEN 'NV'
    WHEN POLICY1.POL_ISS_ST_CD = '28' THEN 'NH'
    WHEN POLICY1.POL_ISS_ST_CD = '29' THEN 'NJ'
    WHEN POLICY1.POL_ISS_ST_CD = '30' THEN 'NM'
    WHEN POLICY1.POL_ISS_ST_CD = '31' THEN 'NY'
    WHEN POLICY1.POL_ISS_ST_CD = '32' THEN 'NC'
    WHEN POLICY1.POL_ISS_ST_CD = '33' THEN 'ND'
    WHEN POLICY1.POL_ISS_ST_CD = '34' THEN 'OH'
    WHEN POLICY1.POL_ISS_ST_CD = '35' THEN 'OK'
    WHEN POLICY1.POL_ISS_ST_CD = '36' THEN 'OR'
    WHEN POLICY1.POL_ISS_ST_CD = '37' THEN 'PA'
    WHEN POLICY1.POL_ISS_ST_CD = '38' THEN 'RI'
    WHEN POLICY1.POL_ISS_ST_CD = '39' THEN 'SC'
    WHEN POLICY1.POL_ISS_ST_CD = '40' THEN 'SD'
    WHEN POLICY1.POL_ISS_ST_CD = '41' THEN 'TN'
    WHEN POLICY1.POL_ISS_ST_CD = '42' THEN 'TX'
    WHEN POLICY1.POL_ISS_ST_CD = '43' THEN 'UT'
    WHEN POLICY1.POL_ISS_ST_CD = '44' THEN 'VT'
    WHEN POLICY1.POL_ISS_ST_CD = '45' THEN 'VA'
    WHEN POLICY1.POL_ISS_ST_CD = '46' THEN 'WA'
    WHEN POLICY1.POL_ISS_ST_CD = '47' THEN 'WV'
    WHEN POLICY1.POL_ISS_ST_CD = '48' THEN 'WI'
    WHEN POLICY1.POL_ISS_ST_CD = '49' THEN 'WY'
    WHEN POLICY1.POL_ISS_ST_CD = '50' THEN 'AK'
    WHEN POLICY1.POL_ISS_ST_CD = '51' THEN 'HI'
    WHEN POLICY1.POL_ISS_ST_CD = '52' THEN 'PR'
    ELSE POLICY1.POL_ISS_ST_CD END IssueState
  , RESULTCOV.PLN_DES_SER_CD Plancode
  , RESULTCOV.POL_FRM_NBR FormNumber
  , VARCHAR_FORMAT(RESULTCOV.ISSUE_DT, 'MM/DD/YYYY') IssueDt
  , RESULTCOV.INS_ISS_AGE IssueAge
  , USERGEN.FUZGREIN_IND RGA_Ind
  , COVSUMMARY.TOTAL_SA TotalFace
  , COVSUMMARY.TOTAL_ORIGINAL_SA TotalOriginalFace
  , (POLICY_TOTALS.TOT_REG_PRM_AMT + POLICY_TOTALS.TOT_ADD_PRM_AMT) PremTD
  , POLICY_TOTALS.TOT_WTD_AMT AccumWD
  , PREMWD_FACE.TOTAL_FACE TotalFace
  , ROUND(REAL(PREMWD_FACE.TOTAL_FACE) + COALESCE(REAL(MVVAL.OPTDB), 0), 2) DeathBenefit
  , NONTRAD.DTH_BNF_PLN_OPT_CD DBOpt
  , SUBSTR(POLICY1.USR_RES_CD, 1, 1) MDO
  , COVERAGE1.DIV_PTP_TYP_CD ParticipationCode
  , (CASE WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H') THEN 'Participating' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) IN ('9') THEN 'Participating but divs are paid up' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) IN ('', '0', '1', '2', '3', '4', '5', '6', '7', '8') THEN 'Nonparticipating' ELSE 'Unknown' END) Participation
  , POLICYDEBT.REG_LOAN_PRINCIPLE
  , POLICYDEBT.REG_LOAN_ACCRUED
  , POLICYDEBT.PREF_LOAN_PRINCIPLE
  , POLICYDEBT.PREF_LOAN_ACCRUED
  , (CASE
      WHEN POLICY1.LN_TYP_CD = '0' THEN 'FIX'
      WHEN POLICY1.LN_TYP_CD = '1' THEN 'FIX'
      WHEN POLICY1.LN_TYP_CD = '6' THEN 'VAR'
      WHEN POLICY1.LN_TYP_CD = '7' THEN 'VAR'
      WHEN POLICY1.LN_TYP_CD = '9' THEN 'NA'
      ELSE POLICY1.LN_TYP_CD
      END) LOAN_TYPE
  , (CASE
      WHEN POLICY1.LN_TYP_CD = '0' THEN 'ADVANCE'
      WHEN POLICY1.LN_TYP_CD = '1' THEN 'ARREARS'
      WHEN POLICY1.LN_TYP_CD = '6' THEN 'ADVANCE'
      WHEN POLICY1.LN_TYP_CD = '7' THEN 'ARREARS'
      WHEN POLICY1.LN_TYP_CD = '9' THEN 'NA'
      ELSE POLICY1.LN_TYP_CD
      END) LOAN_TIMING
  , POLICY1.NON_TRD_POL_IND NonTradInd
  , COVERAGE1.INT_RNL_PER InitTermPeriod
  , RIDER1.PLN_DES_SER_CD Rider1Plancode
  , RIDER2.PRD_LIN_TYP_CD Rider2ProdLine
FROM DB2TAB.LH_BAS_POL POLICY1
  INNER JOIN DB2TAB.LH_COV_PHA COVSALL
    ON POLICY1.CK_SYS_CD = COVSALL.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = COVSALL.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = COVSALL.TCH_POL_ID
  INNER JOIN COVERAGE1
    ON POLICY1.CK_SYS_CD = COVERAGE1.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = COVERAGE1.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = COVERAGE1.TCH_POL_ID
  INNER JOIN DB2TAB.LH_COV_PHA RESULTCOV
    ON POLICY1.CK_SYS_CD = RESULTCOV.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = RESULTCOV.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = RESULTCOV.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.TH_USER_GENERIC USERGEN
    ON POLICY1.CK_SYS_CD = USERGEN.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = USERGEN.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = USERGEN.TCH_POL_ID
  INNER JOIN COVSUMMARY
    ON COVSUMMARY.CK_SYS_CD = POLICY1.CK_SYS_CD
    AND COVSUMMARY.CK_CMP_CD = POLICY1.CK_CMP_CD
    AND COVSUMMARY.TCH_POL_ID = POLICY1.TCH_POL_ID
  INNER JOIN PREMWD_FACE
    ON PREMWD_FACE.CK_SYS_CD = POLICY1.CK_SYS_CD
    AND PREMWD_FACE.CK_CMP_CD = POLICY1.CK_CMP_CD
    AND PREMWD_FACE.TCH_POL_ID = POLICY1.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.TH_USER_PDF UPDF
    ON POLICY1.CK_SYS_CD = UPDF.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = UPDF.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = UPDF.TCH_POL_ID
    AND UPDF.TYPE_SEQUENCE = 1
  LEFT OUTER JOIN DB2TAB.LH_TAMRA_7_PY_PER TAMRA
    ON POLICY1.CK_SYS_CD = TAMRA.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = TAMRA.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = TAMRA.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_POL_TOTALS POLICY_TOTALS
    ON POLICY1.CK_SYS_CD = POLICY_TOTALS.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = POLICY_TOTALS.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = POLICY_TOTALS.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_NON_TRD_POL NONTRAD
    ON POLICY1.CK_SYS_CD = NONTRAD.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = NONTRAD.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = NONTRAD.TCH_POL_ID
  INNER JOIN DB2TAB.TH_COV_PHA MODCOVSALL
    ON MODCOVSALL.CK_SYS_CD = COVSALL.CK_SYS_CD
    AND MODCOVSALL.CK_CMP_CD = COVSALL.CK_CMP_CD
    AND MODCOVSALL.TCH_POL_ID = COVSALL.TCH_POL_ID
    AND MODCOVSALL.COV_PHA_NBR = COVSALL.COV_PHA_NBR
    AND MODCOVSALL.AN_PRD_ID IN ('A')
  INNER JOIN DB2TAB.TH_COV_PHA RESULTCOV_MOD
    ON RESULTCOV_MOD.CK_SYS_CD = RESULTCOV.CK_SYS_CD
    AND RESULTCOV_MOD.CK_CMP_CD = RESULTCOV.CK_CMP_CD
    AND RESULTCOV_MOD.TCH_POL_ID = RESULTCOV.TCH_POL_ID
    AND RESULTCOV_MOD.COV_PHA_NBR = RESULTCOV.COV_PHA_NBR
    AND RESULTCOV_MOD.AN_PRD_ID IN ('A')
  LEFT OUTER JOIN DB2TAB.LH_LN_RPY_TRM SLR_BILL_CONTROL
    ON POLICY1.CK_SYS_CD = SLR_BILL_CONTROL.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = SLR_BILL_CONTROL.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = SLR_BILL_CONTROL.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.TH_BAS_POL POLICY1_MOD
    ON POLICY1.CK_SYS_CD = POLICY1_MOD.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = POLICY1_MOD.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = POLICY1_MOD.TCH_POL_ID
  INNER JOIN ALL_LOANS
    ON POLICY1.CK_SYS_CD = ALL_LOANS.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = ALL_LOANS.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = ALL_LOANS.TCH_POL_ID
    AND ALL_LOANS.PRF_LN_IND = '1'
  INNER JOIN POLICYDEBT
    ON POLICY1.CK_SYS_CD = POLICYDEBT.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = POLICYDEBT.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = POLICYDEBT.TCH_POL_ID
  INNER JOIN CHANGE_SEGMENT
    ON POLICY1.CK_SYS_CD = CHANGE_SEGMENT.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = CHANGE_SEGMENT.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = CHANGE_SEGMENT.TCH_POL_ID
  LEFT OUTER JOIN MVVAL
    ON POLICY1.CK_SYS_CD = MVVAL.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = MVVAL.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = MVVAL.TCH_POL_ID
  INNER JOIN ISWL_INTERPOLATED_GCV
    ON POLICY1.CK_SYS_CD = ISWL_INTERPOLATED_GCV.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = ISWL_INTERPOLATED_GCV.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = ISWL_INTERPOLATED_GCV.TCH_POL_ID
  INNER JOIN GLP
    ON POLICY1.CK_SYS_CD = GLP.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = GLP.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = GLP.TCH_POL_ID
  INNER JOIN FUND_VALUES
    ON POLICY1.CK_SYS_CD = FUND_VALUES.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = FUND_VALUES.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = FUND_VALUES.TCH_POL_ID
    AND FUND_VALUES.FND_ID_CD = 'F01'
  INNER JOIN DB2TAB.LH_FND_TRS_ALC_SET ALLOCATION_P_COUNT
    ON POLICY1.CK_SYS_CD = ALLOCATION_P_COUNT.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = ALLOCATION_P_COUNT.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = ALLOCATION_P_COUNT.TCH_POL_ID
    AND ALLOCATION_P_COUNT.FND_TRS_TYP_CD = 'P'
  INNER JOIN DB2TAB.LH_FND_TRS_ALC_SET ALLOCATION_V_COUNT
    ON POLICY1.CK_SYS_CD = ALLOCATION_V_COUNT.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = ALLOCATION_V_COUNT.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = ALLOCATION_V_COUNT.TCH_POL_ID
    AND ALLOCATION_V_COUNT.FND_TRS_TYP_CD = 'V'
  INNER JOIN DB2TAB.LH_COV_PHA RIDER1
    ON POLICY1.CK_SYS_CD = RIDER1.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = RIDER1.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = RIDER1.TCH_POL_ID
    AND RIDER1.COV_PHA_NBR > 1
    AND RIDER1.PLN_DES_SER_CD = '1U535A00'
    AND RIDER1.ISSUE_DT > COVERAGE1.ISSUE_DT
  INNER JOIN DB2TAB.LH_COV_PHA RIDER2
    ON POLICY1.CK_SYS_CD = RIDER2.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = RIDER2.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = RIDER2.TCH_POL_ID
    AND RIDER2.COV_PHA_NBR > 1
    AND RIDER2.PRD_LIN_TYP_CD = '0'
WHERE POLICY1.CK_SYS_CD = 'I'
  AND SUBSTR(POLICY1.SVC_AGC_NBR, 2, 3) = '123'
  AND POLICY1.PRM_PAY_STA_REA_CD IN ('11')
  AND RESULTCOV.PRD_LIN_TYP_CD IN ('0')
  AND POLICY1.POL_ISS_ST_CD IN ('01')
  AND POLICY1.LST_ETR_CD IN ('A')
  AND POLICY1.SUS_CD IN ('0')
  AND POLICY1.BIL_FRM_CD IN ('0')
  AND ((POLICY1.PMT_FQY_PER = 1 AND COALESCE(POLICY1.NSD_MD_CD, '') = ''))
  AND TAMRA.XCG_1035_PMT_QTY > 0
  AND TAMRA.MEC_STA_CD = '1'
  AND NONTRAD.PR_LIMIT_EXC_ONL = '1'
  AND TRIM(COVERAGE1.DIV_PTP_TYP_CD) IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H')
  AND POLICY1.LN_TYP_CD IN ('0')
  AND POLICY1_MOD.OVERLOAN_IND IN ('0')
  AND POLICY1.NON_TRD_POL_IND IN ('0')
  AND SLR_BILL_CONTROL.BIL_FRM_CD IN ('0')
  AND NONTRAD.TFDF_CD IN ('1')
  AND POLICY1.REINSURED_CD IN ('')
  AND CHANGE_SEGMENT.CHG_TYP_CD IN ('1')
  AND (GLP.GLP_VALUE < 0)
  AND (COVSUMMARY.TOTAL_SA < COVSUMMARY.TOTAL_ORIGINAL_SA)
  AND (COVSUMMARY.TOTAL_SA > COVSUMMARY.TOTAL_ORIGINAL_SA)
  AND (ISWL_INTERPOLATED_GCV.ISWL_GCV >= MVVAL.CSV_AMT)
  AND (ISWL_INTERPOLATED_GCV.ISWL_GCV <= MVVAL.CSV_AMT)
  AND ((POLICY_TOTALS.TOT_REG_PRM_AMT + POLICY_TOTALS.TOT_ADD_PRM_AMT - POLICY_TOTALS.TOT_WTD_AMT) > PREMWD_FACE.TOTAL_FACE)
  AND NONTRAD.GRA_THD_RLE_CD IN ('C')
  AND NONTRAD.DTH_BNF_PLN_OPT_CD IN ('1')
  AND EXISTS (SELECT 1 FROM DB2TAB.TH_NON_TRD_POL DECRCHG WHERE DECRCHG.CK_SYS_CD = POLICY1.CK_SYS_CD AND DECRCHG.CK_CMP_CD = POLICY1.CK_CMP_CD AND DECRCHG.TCH_POL_ID = POLICY1.TCH_POL_ID AND (DECRCHG.DECR_CHRG_ALLOW IN ('0')))
  AND POLICY1.OGN_ETR_CD IN ('A')
  AND FUND_VALUES.FUNDAMT >= 10.0
  AND FUND_VALUES.FUNDAMT <= 250.0
  AND ALLOCATION_P_COUNT.FND_ALC_SEQ_NBR >= 1
  AND ALLOCATION_V_COUNT.FND_ALC_SEQ_NBR <= 3
  AND EXISTS (SELECT 1 FROM DB2TAB.LH_COV_FXD_FND_CTL FFC_SRCH WHERE FFC_SRCH.CK_SYS_CD = POLICY1.CK_SYS_CD AND FFC_SRCH.CK_CMP_CD = POLICY1.CK_CMP_CD AND FFC_SRCH.TCH_POL_ID = POLICY1.TCH_POL_ID AND UPPER(TRIM(FFC_SRCH.CUR_ITS_RT_SER_NBR)) = 'CIRF001')
  AND (COVSUMMARY.BASECOVCOUNT > 1)
  AND SUBSTR(POLICY1.USR_RES_CD,1,1) = 'Y'
  AND (CASE WHEN (UPDF.CONVERSION_PERIOD = 0 AND (COVERAGE1.INS_ISS_AGE + TRUNCATE(MONTHS_BETWEEN('2026-09-25', COVERAGE1.ISSUE_DT) / 12, 0)) < UPDF.CONVERSION_AGE) OR (UPDF.CONVERSION_PERIOD > 0 AND TRUNCATE(MONTHS_BETWEEN('2026-09-25', COVERAGE1.ISSUE_DT) / 12, 0) < UPDF.CONVERSION_PERIOD AND (COVERAGE1.INS_ISS_AGE + TRUNCATE(MONTHS_BETWEEN('2026-09-25', COVERAGE1.ISSUE_DT) / 12, 0)) < UPDF.CONVERSION_AGE) THEN 'TRUE' ELSE 'FALSE' END) = 'TRUE'
  AND POLICY1.NON_TRD_POL_IND IN ('0')
  AND COVERAGE1.INT_RNL_PER IN ('0')
  AND (RESULTCOV.COV_PHA_NBR = RIDER1.COV_PHA_NBR OR RESULTCOV.COV_PHA_NBR = RIDER2.COV_PHA_NBR)
FETCH FIRST 25 ROWS ONLY