WITH COVERAGE1 AS
  (SELECT * FROM DB2TAB.LH_COV_PHA C1 WHERE C1.COV_PHA_NBR = 1)
, LH_POL_YR_TOT_withMaxDuration AS
  (SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, MAX(POL_YR_DUR) MAX_DURATION
   FROM DB2TAB.LH_POL_YR_TOT
   GROUP BY CK_SYS_CD, CK_CMP_CD, TCH_POL_ID)
, LH_POL_YR_TOT_at_MaxDuration AS
  (SELECT YEARTOTS.*
   FROM DB2TAB.LH_POL_YR_TOT YEARTOTS
   INNER JOIN LH_POL_YR_TOT_withMaxDuration
     ON YEARTOTS.CK_SYS_CD = LH_POL_YR_TOT_withMaxDuration.CK_SYS_CD
    AND YEARTOTS.CK_CMP_CD = LH_POL_YR_TOT_withMaxDuration.CK_CMP_CD
    AND YEARTOTS.TCH_POL_ID = LH_POL_YR_TOT_withMaxDuration.TCH_POL_ID
    AND YEARTOTS.POL_YR_DUR = LH_POL_YR_TOT_withMaxDuration.MAX_DURATION)
, GRACE_TABLE AS
  (SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, GRA_PER_EXP_DT, IN_GRA_PER_IND
   FROM DB2TAB.LH_NON_TRD_POL
   UNION
   SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, GRA_PER_EXP_DT, IN_GRA_PER_IND
   FROM DB2TAB.LH_TRD_POL)
, CONVERSION_SC AS
  (SELECT CONVERTED_POLICY.CK_SYS_CD, FH.CK_CMP_CD, FH.TCH_POL_ID,
    FH.ENTRY_DT AS CONV_SC_ENTRY_DT, FH.ASOF_DT AS CONV_SC_EFFECTIVE_DT,
    ROW_NUMBER() OVER (
      PARTITION BY CONVERTED_POLICY.CK_SYS_CD, FH.CK_CMP_CD, FH.TCH_POL_ID
      ORDER BY FH.ENTRY_DT DESC NULLS LAST, FH.ENTRY_TIME DESC NULLS LAST,
               FH.SEQ_NO DESC) AS SC_ROW
   FROM DB2TAB.FH_FIXED FH
   INNER JOIN DB2TAB.LH_BAS_POL CONVERTED_POLICY
     ON CONVERTED_POLICY.CK_CMP_CD = FH.CK_CMP_CD
    AND CONVERTED_POLICY.TCH_POL_ID = FH.TCH_POL_ID
    AND CONVERTED_POLICY.LST_ETR_CD = 'O'
   WHERE FH.TRANS = 'SC'
     AND FH.FCB0_REV_IND = '0'
     AND FH.FCB2_REV_APPL_IND = '0')
, POST_CONVERSION AS
  (SELECT DISTINCT G.CK_SYS_CD,
    TRIM(G.SOURCE_CMP_CODE) AS SOURCE_CMP_CODE,
    TRIM(G.EXCH_POL_NUMBER) AS SOURCE_POLICY_NBR,
    DEST.CK_CMP_CD AS POST_CONV_COMPANY,
    DEST.CK_POLICY_NBR AS POST_CONV_POLICY
   FROM DB2TAB.TH_USER_GENERIC G
   INNER JOIN DB2TAB.LH_BAS_POL DEST
     ON G.CK_SYS_CD = DEST.CK_SYS_CD
    AND G.CK_CMP_CD = DEST.CK_CMP_CD
    AND G.TCH_POL_ID = DEST.TCH_POL_ID
   WHERE TRIM(G.SOURCE_CMP_CODE) <> ''
     AND TRIM(G.EXCH_POL_NUMBER) <> '')
, TERMINATION_TRANS AS
  (SELECT FH.CK_CMP_CD, FH.TCH_POL_ID,
    FH.ENTRY_DT, FH.ASOF_DT, FH.TRANS
   FROM DB2TAB.FH_FIXED AS FH
   WHERE FH.TRANS IN ('SC', 'SI', 'SF', 'TD', 'TM', 'TN', 'TL', 'TO')
   AND FH.FCB0_REV_IND = '0'
   AND FH.FCB2_REV_APPL_IND = '0')
, PRE_TERMINATION_DATES AS
  (SELECT TT.CK_CMP_CD, TT.TCH_POL_ID,
   MAX(TT.ENTRY_DT) AS TERM_ENTRY_DT
   FROM TERMINATION_TRANS AS TT
   GROUP BY TT.CK_CMP_CD, TT.TCH_POL_ID)
, TERMINATION_ENTRY_EFFECTIVE_DATES AS
  (SELECT CK_CMP_CD, TCH_POL_ID, ENTRY_DT,
    MAX(ASOF_DT) AS TERM_EFFECTIVE_DT
   FROM TERMINATION_TRANS
   GROUP BY CK_CMP_CD, TCH_POL_ID, ENTRY_DT)
, TERMINATION_ENTRY_TRANS_TYPES AS
  (SELECT CK_CMP_CD, TCH_POL_ID, ENTRY_DT,
    MAX(CASE WHEN TRANS = 'SC' THEN 1 ELSE 0 END) AS HAS_SC,
    MAX(CASE WHEN TRANS = 'SI' THEN 1 ELSE 0 END) AS HAS_SI,
    MAX(CASE WHEN TRANS = 'SF' THEN 1 ELSE 0 END) AS HAS_SF,
    MAX(CASE WHEN TRANS = 'TD' THEN 1 ELSE 0 END) AS HAS_TD,
    MAX(CASE WHEN TRANS = 'TM' THEN 1 ELSE 0 END) AS HAS_TM,
    MAX(CASE WHEN TRANS = 'TN' THEN 1 ELSE 0 END) AS HAS_TN,
    MAX(CASE WHEN TRANS = 'TL' THEN 1 ELSE 0 END) AS HAS_TL,
    MAX(CASE WHEN TRANS = 'TO' THEN 1 ELSE 0 END) AS HAS_TO
   FROM TERMINATION_TRANS
   GROUP BY CK_CMP_CD, TCH_POL_ID, ENTRY_DT)
, TERMINATION_ENTRY_DETAILS AS
  (SELECT PTD.CK_CMP_CD, PTD.TCH_POL_ID, PTD.TERM_ENTRY_DT,
    TED.TERM_EFFECTIVE_DT,
    SUBSTR(
      CASE WHEN TTT.HAS_SC = 1 THEN ', SC' ELSE '' END ||
      CASE WHEN TTT.HAS_SI = 1 THEN ', SI' ELSE '' END ||
      CASE WHEN TTT.HAS_SF = 1 THEN ', SF' ELSE '' END ||
      CASE WHEN TTT.HAS_TD = 1 THEN ', TD' ELSE '' END ||
      CASE WHEN TTT.HAS_TM = 1 THEN ', TM' ELSE '' END ||
      CASE WHEN TTT.HAS_TN = 1 THEN ', TN' ELSE '' END ||
      CASE WHEN TTT.HAS_TL = 1 THEN ', TL' ELSE '' END ||
      CASE WHEN TTT.HAS_TO = 1 THEN ', TO' ELSE '' END,
      3) AS TERM_TRANS_TYPES
   FROM PRE_TERMINATION_DATES AS PTD
   INNER JOIN TERMINATION_ENTRY_EFFECTIVE_DATES AS TED
     ON PTD.CK_CMP_CD = TED.CK_CMP_CD
    AND PTD.TCH_POL_ID = TED.TCH_POL_ID
    AND PTD.TERM_ENTRY_DT = TED.ENTRY_DT
   INNER JOIN TERMINATION_ENTRY_TRANS_TYPES AS TTT
     ON PTD.CK_CMP_CD = TTT.CK_CMP_CD
    AND PTD.TCH_POL_ID = TTT.TCH_POL_ID
    AND PTD.TERM_ENTRY_DT = TTT.ENTRY_DT)
, TERMINATION_DATES AS
  (SELECT * FROM TERMINATION_ENTRY_DETAILS)
, ALL_LOANS AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, PRF_LN_IND, LN_PRI_AMT,
    (CASE LN_ITS_AMT_TYP_CD WHEN '2' THEN POL_LN_ITS_AMT ELSE 0 END) LN_INT
  FROM DB2TAB.LH_FND_VAL_LOAN WHERE MVRY_DT = '9999-12-31'
  UNION
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, PRF_LN_IND, LN_PRI_AMT,
    (CASE LN_ITS_AMT_TYP_CD WHEN '2' THEN POL_LN_ITS_AMT ELSE 0 END) LN_INT
  FROM DB2TAB.LH_CSH_VAL_LOAN WHERE MVRY_DT = '9999-12-31')
, POLICYDEBT AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID,
    SUM(ALL_LOANS.LN_PRI_AMT) LOAN_PRINCIPLE,
    SUM(ALL_LOANS.LN_INT) LOAN_ACCRUED,
    SUM(CASE WHEN COALESCE(ALL_LOANS.PRF_LN_IND, '0') <> '1'
      THEN ALL_LOANS.LN_PRI_AMT ELSE 0 END) REG_LOAN_PRINCIPLE,
    SUM(CASE WHEN COALESCE(ALL_LOANS.PRF_LN_IND, '0') <> '1'
      THEN ALL_LOANS.LN_INT ELSE 0 END) REG_LOAN_ACCRUED,
    SUM(CASE WHEN ALL_LOANS.PRF_LN_IND = '1'
      THEN ALL_LOANS.LN_PRI_AMT ELSE 0 END) PREF_LOAN_PRINCIPLE,
    SUM(CASE WHEN ALL_LOANS.PRF_LN_IND = '1'
      THEN ALL_LOANS.LN_INT ELSE 0 END) PREF_LOAN_ACCRUED
  FROM ALL_LOANS
  GROUP BY CK_SYS_CD, CK_CMP_CD, TCH_POL_ID)
, BILLMODE_POOL AS
  (SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID,
   PMT_FQY_PER, NSD_MD_CD
   FROM DB2TAB.LH_BAS_POL)
, ALL_BASE_COVS AS (
  SELECT TEMPCOV1.CK_SYS_CD, TEMPCOV1.TCH_POL_ID, TEMPCOV1.CK_CMP_CD
    , TEMPCOVALL.COV_PHA_NBR
    , ROUND(REAL(TEMPCOVALL.COV_UNT_QTY) * REAL(TEMPCOVALL.COV_VPU_AMT), 2) SPECAMT
    , ROUND(REAL(TEMPCOVALL.OGN_SPC_UNT_QTY) * REAL(TEMPCOVALL.COV_VPU_AMT), 2) ORIGSPECAMT
  FROM DB2TAB.LH_COV_PHA TEMPCOV1
    INNER JOIN DB2TAB.LH_COV_PHA TEMPCOVALL
      ON TEMPCOV1.COV_PHA_NBR = 1
      AND TEMPCOV1.CK_SYS_CD = TEMPCOVALL.CK_SYS_CD
      AND TEMPCOV1.CK_CMP_CD = TEMPCOVALL.CK_CMP_CD
      AND TEMPCOV1.TCH_POL_ID = TEMPCOVALL.TCH_POL_ID
      AND (TEMPCOVALL.PLN_DES_SER_CD = TEMPCOV1.PLN_DES_SER_CD))
, COVSUMMARY AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID
    , SUM(ALL_BASE_COVS.SPECAMT) TOTAL_SA
    , SUM(ALL_BASE_COVS.ORIGSPECAMT) TOTAL_ORIGINAL_SA
  FROM ALL_BASE_COVS
  GROUP BY CK_SYS_CD, CK_CMP_CD, TCH_POL_ID)
, LASTMV AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, MAX(MVRY_DT) LASTMVDT
  FROM DB2TAB.LH_POL_MVRY_VAL
  GROUP BY CK_SYS_CD, CK_CMP_CD, TCH_POL_ID)
, MVVAL AS (
  SELECT MV.CK_SYS_CD, MV.CK_CMP_CD, MV.TCH_POL_ID, MV.CSV_AMT
    , LASTMV.LASTMVDT
    , ROUND(REAL(MV.CSV_AMT) * REAL(ADVPROD.CDR_PCT)/100, 2) DB
    , CASE ADVPROD.DTH_BNF_PLN_OPT_CD
        WHEN '1' THEN 0
        WHEN '2' THEN REAL(MV.CSV_AMT)
        WHEN '3' THEN (TEMPPOLTOTALS.TOT_REG_PRM_AMT + TEMPPOLTOTALS.TOT_ADD_PRM_AMT)
        ELSE 0 END OPTDB
    , (TEMPPOLTOTALS.TOT_REG_PRM_AMT + TEMPPOLTOTALS.TOT_ADD_PRM_AMT) TOTALPREM
  FROM DB2TAB.LH_POL_MVRY_VAL MV
    INNER JOIN LASTMV ON MV.CK_SYS_CD = LASTMV.CK_SYS_CD
      AND MV.CK_CMP_CD = LASTMV.CK_CMP_CD
      AND MV.TCH_POL_ID = LASTMV.TCH_POL_ID
      AND MV.MVRY_DT = LASTMV.LASTMVDT
    INNER JOIN DB2TAB.LH_NON_TRD_POL ADVPROD
      ON MV.CK_SYS_CD = ADVPROD.CK_SYS_CD
      AND MV.CK_CMP_CD = ADVPROD.CK_CMP_CD
      AND MV.TCH_POL_ID = ADVPROD.TCH_POL_ID
    INNER JOIN DB2TAB.LH_POL_TOTALS TEMPPOLTOTALS
      ON MV.CK_SYS_CD = TEMPPOLTOTALS.CK_SYS_CD
      AND MV.CK_CMP_CD = TEMPPOLTOTALS.CK_CMP_CD
      AND MV.TCH_POL_ID = TEMPPOLTOTALS.TCH_POL_ID)
, MONTHLY_DED AS (
  SELECT MV.CK_SYS_CD, MV.CK_CMP_CD, MV.TCH_POL_ID
    , (COALESCE(MV.CINS_AMT, 0) + COALESCE(MV.OTH_PRM_AMT, 0) + COALESCE(MV.EXP_CRG_AMT, 0)) MONTHLY_DED_AMT
    , MV.MVRY_DT MONTHLY_DED_DT
  FROM DB2TAB.LH_POL_MVRY_VAL MV
  WHERE MV.MVRY_DT = (
    SELECT MAX(MV2.MVRY_DT) FROM DB2TAB.LH_POL_MVRY_VAL MV2
    WHERE MV2.CK_SYS_CD = MV.CK_SYS_CD
      AND MV2.CK_CMP_CD = MV.CK_CMP_CD
      AND MV2.TCH_POL_ID = MV.TCH_POL_ID))
, INTERPOLATION_MONTHS AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID
    , REAL(12 - MONTHS_BETWEEN(BASPOL.NXT_MVRY_PRC_DT, BASPOL.LST_ANV_DT)) MONTHS_TO_NEXT_ANN
    , REAL(MONTHS_BETWEEN(BASPOL.NXT_MVRY_PRC_DT, BASPOL.LST_ANV_DT)) MONTHS_YTD
  FROM DB2TAB.LH_BAS_POL BASPOL)
, TRAD_CV AS (
  SELECT COVERAGE1.CK_SYS_CD, COVERAGE1.CK_CMP_CD, COVERAGE1.TCH_POL_ID
    , (CASE WHEN COVERAGE1.LOW_DUR_1_CSV_AMT IS NULL THEN 0
            ELSE COVERAGE1.LOW_DUR_1_CSV_AMT END)
      * COVERAGE1.COV_UNT_QTY/12 * INTERPOLATION_MONTHS.MONTHS_TO_NEXT_ANN
      + (CASE WHEN COVERAGE1.LOW_DUR_2_CSV_AMT IS NULL THEN 0
              ELSE COVERAGE1.LOW_DUR_2_CSV_AMT END)
      * COVERAGE1.COV_UNT_QTY/12 * INTERPOLATION_MONTHS.MONTHS_YTD  INTERP_CV
    , (CASE WHEN COVERAGE1.LOW_DUR_NSP_AMT IS NULL THEN 0
            ELSE COVERAGE1.LOW_DUR_NSP_AMT END)
      * COVERAGE1.COV_UNT_QTY/12 * INTERPOLATION_MONTHS.MONTHS_TO_NEXT_ANN
      + (CASE WHEN COVERAGE1.LOW_DUR_1_NSP_AMT IS NULL THEN 0
              ELSE COVERAGE1.LOW_DUR_1_NSP_AMT END)
      * COVERAGE1.COV_UNT_QTY/12 * INTERPOLATION_MONTHS.MONTHS_YTD  INTERP_NSP
  FROM COVERAGE1
    INNER JOIN INTERPOLATION_MONTHS
      ON COVERAGE1.CK_SYS_CD = INTERPOLATION_MONTHS.CK_SYS_CD
      AND COVERAGE1.CK_CMP_CD = INTERPOLATION_MONTHS.CK_CMP_CD
      AND COVERAGE1.TCH_POL_ID = INTERPOLATION_MONTHS.TCH_POL_ID)
, GLP AS (
  SELECT DISTINCT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID,
    TEMPGLP.GDL_PRM_AMT GLP_VALUE
  FROM DB2TAB.LH_COV_INS_GDL_PRM TEMPGLP
  WHERE TEMPGLP.COV_PHA_NBR = 1
    AND TEMPGLP.PRM_RT_TYP_CD = 'A')
, GSP AS (
  SELECT DISTINCT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID,
    TEMPGSP.GDL_PRM_AMT GSP_VALUE
  FROM DB2TAB.LH_COV_INS_GDL_PRM TEMPGSP
  WHERE TEMPGSP.COV_PHA_NBR = 1
    AND TEMPGSP.PRM_RT_TYP_CD = 'S')
, CHANGE_TYPE9 AS (
  SELECT TMN.CK_SYS_CD, TMN.CK_CMP_CD, TMN.TCH_POL_ID
    , SUM(TMN.OGN_COV_UNT_QTY) TOTALORIGUNITS
  FROM DB2TAB.LH_COV_TMN TMN
    INNER JOIN DB2TAB.LH_NT_COV_CHG COVCHG
      ON COVCHG.CK_SYS_CD = TMN.CK_SYS_CD
      AND COVCHG.CK_CMP_CD = TMN.CK_CMP_CD
      AND COVCHG.TCH_POL_ID = TMN.TCH_POL_ID
      AND COVCHG.COV_PHA_NBR = TMN.COV_PHA_NBR
      AND COVCHG.CHG_TYP_CD = '9'
  GROUP BY TMN.CK_SYS_CD, TMN.CK_CMP_CD, TMN.TCH_POL_ID)
, INSURED1_INFO AS (
  SELECT T1.CK_SYS_CD, T1.CK_CMP_CD, T1.TCH_POL_ID
    , T2.CK_FST_NM FNAME
    , T2.CK_LST_NM LNAME
    , T1.BIR_DT BIRTHDT
  FROM DB2TAB.LH_CTT_CLIENT T1
    INNER JOIN DB2TAB.VH_POL_HAS_LOC_CLT T2
      ON T1.PRS_SEQ_NBR = T2.PRS_SEQ_NBR
      AND T1.PRS_CD = T2.PRS_CD
      AND T1.TCH_POL_ID = T2.TCH_POL_ID
      AND T1.CK_SYS_CD = T2.CK_SYS_CD
      AND T1.CK_CMP_CD = T2.CK_CMP_CD
  WHERE T1.PRS_CD = '00')

SELECT DISTINCT
  CURRENT_DATE RunDate
  , POLICY1.CK_POLICY_NBR PolicyNumber
  , POLICY1.CK_CMP_CD CompanyCode
  , POLICY1.PRM_PAY_STA_REA_CD StatusCode
  , POLICY1.SUS_CD SuspenseCode
  , SUBSTR(POLICY1.SVC_AGC_NBR, 1, 1) AgentCode
  , CASE WHEN POLICY1.POL_ISS_ST_CD = '01' THEN 'AL'
    WHEN POLICY1.POL_ISS_ST_CD = '02' THEN 'AZ'
    WHEN POLICY1.POL_ISS_ST_CD = '03' THEN 'AR'
    WHEN POLICY1.POL_ISS_ST_CD = '04' THEN 'CA'
    WHEN POLICY1.POL_ISS_ST_CD = '05' THEN 'CO'
    WHEN POLICY1.POL_ISS_ST_CD = '06' THEN 'CT'
    WHEN POLICY1.POL_ISS_ST_CD = '07' THEN 'DE'
    WHEN POLICY1.POL_ISS_ST_CD = '08' THEN 'DC'
    WHEN POLICY1.POL_ISS_ST_CD = '09' THEN 'FL'
    WHEN POLICY1.POL_ISS_ST_CD = '10' THEN 'GA'
    WHEN POLICY1.POL_ISS_ST_CD = '11' THEN 'ID'
    WHEN POLICY1.POL_ISS_ST_CD = '12' THEN 'IL'
    WHEN POLICY1.POL_ISS_ST_CD = '13' THEN 'IN'
    WHEN POLICY1.POL_ISS_ST_CD = '14' THEN 'IA'
    WHEN POLICY1.POL_ISS_ST_CD = '15' THEN 'KS'
    WHEN POLICY1.POL_ISS_ST_CD = '16' THEN 'KY'
    WHEN POLICY1.POL_ISS_ST_CD = '17' THEN 'LA'
    WHEN POLICY1.POL_ISS_ST_CD = '18' THEN 'ME'
    WHEN POLICY1.POL_ISS_ST_CD = '19' THEN 'MD'
    WHEN POLICY1.POL_ISS_ST_CD = '20' THEN 'MA'
    WHEN POLICY1.POL_ISS_ST_CD = '21' THEN 'MI'
    WHEN POLICY1.POL_ISS_ST_CD = '22' THEN 'MN'
    WHEN POLICY1.POL_ISS_ST_CD = '23' THEN 'MS'
    WHEN POLICY1.POL_ISS_ST_CD = '24' THEN 'MO'
    WHEN POLICY1.POL_ISS_ST_CD = '25' THEN 'MT'
    WHEN POLICY1.POL_ISS_ST_CD = '26' THEN 'NE'
    WHEN POLICY1.POL_ISS_ST_CD = '27' THEN 'NV'
    WHEN POLICY1.POL_ISS_ST_CD = '28' THEN 'NH'
    WHEN POLICY1.POL_ISS_ST_CD = '29' THEN 'NJ'
    WHEN POLICY1.POL_ISS_ST_CD = '30' THEN 'NM'
    WHEN POLICY1.POL_ISS_ST_CD = '31' THEN 'NY'
    WHEN POLICY1.POL_ISS_ST_CD = '32' THEN 'NC'
    WHEN POLICY1.POL_ISS_ST_CD = '33' THEN 'ND'
    WHEN POLICY1.POL_ISS_ST_CD = '34' THEN 'OH'
    WHEN POLICY1.POL_ISS_ST_CD = '35' THEN 'OK'
    WHEN POLICY1.POL_ISS_ST_CD = '36' THEN 'OR'
    WHEN POLICY1.POL_ISS_ST_CD = '37' THEN 'PA'
    WHEN POLICY1.POL_ISS_ST_CD = '38' THEN 'RI'
    WHEN POLICY1.POL_ISS_ST_CD = '39' THEN 'SC'
    WHEN POLICY1.POL_ISS_ST_CD = '40' THEN 'SD'
    WHEN POLICY1.POL_ISS_ST_CD = '41' THEN 'TN'
    WHEN POLICY1.POL_ISS_ST_CD = '42' THEN 'TX'
    WHEN POLICY1.POL_ISS_ST_CD = '43' THEN 'UT'
    WHEN POLICY1.POL_ISS_ST_CD = '44' THEN 'VT'
    WHEN POLICY1.POL_ISS_ST_CD = '45' THEN 'VA'
    WHEN POLICY1.POL_ISS_ST_CD = '46' THEN 'WA'
    WHEN POLICY1.POL_ISS_ST_CD = '47' THEN 'WV'
    WHEN POLICY1.POL_ISS_ST_CD = '48' THEN 'WI'
    WHEN POLICY1.POL_ISS_ST_CD = '49' THEN 'WY'
    WHEN POLICY1.POL_ISS_ST_CD = '50' THEN 'AK'
    WHEN POLICY1.POL_ISS_ST_CD = '51' THEN 'HI'
    WHEN POLICY1.POL_ISS_ST_CD = '52' THEN 'PR'
    ELSE POLICY1.POL_ISS_ST_CD END IssueState
  , COVERAGE1.PLN_DES_SER_CD Plancode
  , COVERAGE1.POL_FRM_NBR FormNumber
  , VARCHAR_FORMAT(COVERAGE1.ISSUE_DT, 'MM/DD/YYYY') IssueDt
  , COVERAGE1.INS_ISS_AGE IssueAge
  , USERGEN.FUZGREIN_IND RGA_Ind
  , VARCHAR_FORMAT(POLICY1.PRM_PAID_TO_DT, 'MM/DD/YYYY') PaidToDate_Disp
  , VARCHAR_FORMAT(POLICY1.PRM_BILL_TO_DT, 'MM/DD/YYYY') BillToDate
  , INTEGER(TRUNCATE(MONTHS_BETWEEN(COALESCE(CASE WHEN POLICY1.NON_TRD_POL_IND = '1' THEN (SELECT MAX(MV.MVRY_DT) FROM DB2TAB.LH_POL_MVRY_VAL MV WHERE MV.CK_SYS_CD = POLICY1.CK_SYS_CD AND MV.CK_CMP_CD = POLICY1.CK_CMP_CD AND MV.TCH_POL_ID = POLICY1.TCH_POL_ID AND YEAR(MV.MVRY_DT) < 9999) END, CASE WHEN POLICY1.NXT_MVRY_PRC_DT IS NOT NULL AND YEAR(POLICY1.NXT_MVRY_PRC_DT) < 9999 THEN POLICY1.NXT_MVRY_PRC_DT - 1 MONTH END, CASE WHEN POLICY1.LST_FIN_DT IS NOT NULL AND YEAR(POLICY1.LST_FIN_DT) < 9999 THEN POLICY1.LST_FIN_DT END), COVERAGE1.ISSUE_DT) / 12, 0)) ValDuration
  , INTEGER(COVERAGE1.INS_ISS_AGE + TRUNCATE(MONTHS_BETWEEN(COALESCE(CASE WHEN POLICY1.NON_TRD_POL_IND = '1' THEN (SELECT MAX(MV.MVRY_DT) FROM DB2TAB.LH_POL_MVRY_VAL MV WHERE MV.CK_SYS_CD = POLICY1.CK_SYS_CD AND MV.CK_CMP_CD = POLICY1.CK_CMP_CD AND MV.TCH_POL_ID = POLICY1.TCH_POL_ID AND YEAR(MV.MVRY_DT) < 9999) END, CASE WHEN POLICY1.NXT_MVRY_PRC_DT IS NOT NULL AND YEAR(POLICY1.NXT_MVRY_PRC_DT) < 9999 THEN POLICY1.NXT_MVRY_PRC_DT - 1 MONTH END, CASE WHEN POLICY1.LST_FIN_DT IS NOT NULL AND YEAR(POLICY1.LST_FIN_DT) < 9999 THEN POLICY1.LST_FIN_DT END), COVERAGE1.ISSUE_DT) / 12, 0)) ValAttainedAge_Disp
  , VARCHAR_FORMAT(POLICY1.LST_ACT_TRS_DT, 'MM/DD/YYYY') LastAcctDate
  , VARCHAR_FORMAT(POLICY1.LST_FIN_DT, 'MM/DD/YYYY') LastFinDate
  , IFNULL(POLICY1.POL_PRM_AMT, 0) BillPrem
  , (CASE BILLMODE_POOL.PMT_FQY_PER
      WHEN 1 THEN (CASE BILLMODE_POOL.NSD_MD_CD
        WHEN '2' THEN 'BiWeekly'
        WHEN 'S' THEN 'SemiMonthly'
        WHEN '9' THEN '9thly'
        WHEN 'A' THEN '10thly'
        ELSE 'Monthly' END)
      WHEN 3 THEN 'Quarterly'
      WHEN 6 THEN 'SemiAnnually'
      WHEN 12 THEN 'Annually'
      ELSE ' ' END) BillMode
  , POLICY1.BIL_FRM_CD BillForm
  , SUBSTR(POLICY1.SVC_AGC_NBR, 1, 1) MarkOrg
  , POLICY1.REINSURED_CD ReinsuredCode
  , POLICY1.LST_ETR_CD LastEntryCode
  , VARCHAR_FORMAT(POLICY1.LST_FIN_DT, 'MM/DD/YYYY') LastFinDate_Entry
  , POLICY1.OGN_ETR_CD OrigEntryCode
  , COVSUMMARY.TOTAL_SA TotalFace
  , COVSUMMARY.TOTAL_ORIGINAL_SA TotalOriginalFace
  , POLICY1.TCH_POL_ID TCH_POL_ID
  , SUBSTR(POLICY1.USR_RES_CD, 1, 1) MDO
  , COVERAGE1.PRD_LIN_TYP_CD
  , COVERAGE1.INS_SEX_CD SEX_CD
  , COVERAGE1.LIF_PLN_SUB_SRE_CD SUBSERIES
  , (CASE
      WHEN POLICY1.MEC_STATUS_CD = '0' THEN '0 - NO'
      WHEN POLICY1.MEC_STATUS_CD = '1' THEN '1 - YES'
      WHEN POLICY1.MEC_STATUS_CD = '2' THEN '2 - NO'
      ELSE POLICY1.MEC_STATUS_CD
      END) MEC_INDICATOR_01
  , VARCHAR_FORMAT(POLICY1.APP_WRT_DT, 'MM/DD/YYYY') AppDt
  , VARCHAR_FORMAT(POLICY1.NXT_SCH_NOT_DT, 'MM/DD/YYYY') NextNotifyDt
  , VARCHAR_FORMAT(POLICY1.NXT_YR_END_PRC_DT, 'MM/DD/YYYY') NextYearEndDt
  , VARCHAR_FORMAT(POLICY1.NXT_SCH_STT_DT, 'MM/DD/YYYY') NextStatementDt
  , COVERAGE1.NXT_CHG_TYP_CD NXT_CHG_TYP_CD
  , VARCHAR_FORMAT(COVERAGE1.NXT_CHG_DT, 'MM/DD/YYYY') NXT_CHG_DT
  , COVERAGE1.INT_RNL_PER
  , COVERAGE1.SBQ_RNL_STR_DUR
  , COVERAGE1.SBQ_RNL_PER
  , COMMTARGET.TAR_PRM_AMT CTP
  , MTP.TAR_PRM_AMT MonthlyMTP
  , ACCUMMTP.TAR_PRM_AMT ACCUMMTP
  , ACCUMGLP.TAR_PRM_AMT ACCUMGLP
  , NSPTARGET.TAR_PRM_AMT NSP
  , SHADOWAV.TAR_PRM_AMT ShadowAV
  , NONTRAD.DTH_BNF_PLN_OPT_CD DBOpt
  , (CASE
      WHEN NONTRAD.TFDF_CD = '1' THEN '1 - GPT TEFRA'
      WHEN NONTRAD.TFDF_CD = '2' THEN '2 - GPT DEFRA'
      WHEN NONTRAD.TFDF_CD = '3' THEN '3 - CVAT DEFRA'
      WHEN NONTRAD.TFDF_CD = '4' THEN '4 - GPT Selected'
      WHEN NONTRAD.TFDF_CD = '5' THEN '5 - CVAT Selected'
      ELSE NONTRAD.TFDF_CD
      END) DefOfLifeIns
  , SHORTPAY_PRM.TAR_PRM_AMT SHORTPAY_AMT
  , VARCHAR_FORMAT(SHORTPAY_PRM.TAR_DT, 'MM/DD/YYYY') SHORTPAY_CEASEDT
  , USERDEF_52G.INITIAL_PAY_DUR SHORTPAY_DUR
  , USERDEF_52G.INITIAL_MODE SHORTPAY_MODE
  , USERDEF_52G.DIAL_TO_PREM_AGE SHORTPAY_DBAGE
  , VARCHAR_FORMAT(GRACE_TABLE.GRA_PER_EXP_DT, 'MM/DD/YYYY') GPE_DT
  , VARCHAR_FORMAT(TD.TERM_ENTRY_DT, 'MM/DD/YYYY') TERM_ENTRY_DT
  , VARCHAR_FORMAT(TD.TERM_EFFECTIVE_DT, 'MM/DD/YYYY') TERM_EFFECTIVE_DT
  , TD.TERM_TRANS_TYPES
  , VARCHAR_FORMAT(SC.CONV_SC_ENTRY_DT, 'MM/DD/YYYY') CONV_SC_ENTRY_DT
  , VARCHAR_FORMAT(SC.CONV_SC_EFFECTIVE_DT, 'MM/DD/YYYY') CONV_SC_EFFECTIVE_DT
  , POLICY_TOTALS.TOT_WTD_AMT
  , POLICY_TOTALS.POL_CST_BSS_AMT COSTBASIS
  , VARCHAR_FORMAT(MVVAL.LASTMVDT, 'MM/DD/YYYY') LastMonthliverary
  , MVVAL.CSV_AMT CurrCV
  , MVVAL.TOTALPREM
  , LH_POL_YR_TOT_at_MaxDuration.YTD_TOT_PMT_AMT
  , MONTHLY_DED.MONTHLY_DED_AMT
  , VARCHAR_FORMAT(MONTHLY_DED.MONTHLY_DED_DT, 'MM/DD/YYYY') MONTHLY_DED_DT
  , POLICYDEBT.LOAN_PRINCIPLE
  , POLICYDEBT.LOAN_ACCRUED
  , (CASE
      WHEN POLICY1.LN_TYP_CD = '0' THEN 'FIX'
      WHEN POLICY1.LN_TYP_CD = '1' THEN 'FIX'
      WHEN POLICY1.LN_TYP_CD = '6' THEN 'VAR'
      WHEN POLICY1.LN_TYP_CD = '7' THEN 'VAR'
      WHEN POLICY1.LN_TYP_CD = '9' THEN 'NA'
      ELSE POLICY1.LN_TYP_CD
      END) LOAN_TYPE
  , (CASE
      WHEN POLICY1.LN_TYP_CD = '0' THEN 'ADVANCE'
      WHEN POLICY1.LN_TYP_CD = '1' THEN 'ARREARS'
      WHEN POLICY1.LN_TYP_CD = '6' THEN 'ADVANCE'
      WHEN POLICY1.LN_TYP_CD = '7' THEN 'ARREARS'
      WHEN POLICY1.LN_TYP_CD = '9' THEN 'NA'
      ELSE POLICY1.LN_TYP_CD
      END) LOAN_TIMING
  , (CASE WHEN TABLE_RATING1.SST_XTR_RT_TBL_CD IS NULL THEN ' ' ELSE TABLE_RATING1.SST_XTR_RT_TBL_CD END) TableRating
  , (CASE WHEN FLAT_EXTRA1.SST_XTR_UNT_AMT IS NULL THEN '0' ELSE FLAT_EXTRA1.SST_XTR_UNT_AMT END) MONTHFLAT
  , COV1_RENEWALS.RT_CLS_CD RenewalClass
  , COV1_RENEWALS.RT_SEX_CD RenewalSex
  , COV1_RENEWALS.RT_BAN_CD RenewalBand
  , TAMRA.SVPY_LVL_PRM_AMT TAMRA7PAY
  , GSP.GSP_VALUE
  , GLP.GLP_VALUE
  , BILL_CONTROL.BIL_CTL_NBR BillControl
  , SLR_BILL_CONTROL.BIL_FRM_CD SLRBillForm
  , CHANGE_TYPE9.TOTALORIGUNITS
  , FIXPREM.MD_PRM_MUL_ORD_CD
  , FIXPREM.RT_FCT_ORD_CD
  , FIXPREM.ROU_RLE_CD
  , FFC.CUR_ITS_RT_SER_NBR CIRF_Key
  , POLICY1_MOD.OVERLOAN_IND
  , USERDEF_52R.REPLACED_POLICY REPLACED_POL
  , USERGEN.SOURCE_CMP_CODE SOURCE_CMP_CODE
  , USERGEN.EXCH_POL_NUMBER EXCHANGE_POL
  , USERGEN.EXCHANGE EXCHANGE_CD
  , USERGEN.SOURCE_COV_PHASE CONV_COV
  , USERGEN.SOURCE_ISSUE_DATE CONV_ISSDT
  , USERGEN.SOURCE_PLAN_CODE CONV_PLAN
  , USERGEN.SOURCE_FACE_AMT CONV_FACE
  , PC.POST_CONV_POLICY
  , PC.POST_CONV_COMPANY
  , UPDF.CONV_CREDIT_IND CN_CRED_IND
  , UPDF.CONV_CREDIT_RULE CN_CRED_RULE
  , UPDF.CONV_CREDIT_PERIOD CN_CRED_PERIOD
  , (CASE
      WHEN (UPDF.CONVERSION_PERIOD = 0 AND (COVERAGE1.INS_ISS_AGE + TRUNCATE(MONTHS_BETWEEN('2026-09-25', COVERAGE1.ISSUE_DT) / 12, 0)) < UPDF.CONVERSION_AGE)
        OR (UPDF.CONVERSION_PERIOD > 0 AND TRUNCATE(MONTHS_BETWEEN('2026-09-25', COVERAGE1.ISSUE_DT) / 12, 0) < UPDF.CONVERSION_PERIOD
            AND (COVERAGE1.INS_ISS_AGE + TRUNCATE(MONTHS_BETWEEN('2026-09-25', COVERAGE1.ISSUE_DT) / 12, 0)) < UPDF.CONVERSION_AGE)
      THEN 'TRUE' ELSE 'FALSE'
      END) AS WITHIN_CONV_PERIOD
  , UPDF.CONVERSION_PERIOD CN_PERIOD
  , UPDF.CONVERSION_AGE CN_AGE
  , UPDF.CONV_TO_TRM_PERIOD CN_TO_TERM_PERIOD
  , (CASE
      WHEN COALESCE(COVERAGE1.LOW_DUR_1_CSV_AMT, 0) <> 0 OR COALESCE(COVERAGE1.LOW_DUR_2_CSV_AMT, 0) <> 0
      THEN COALESCE(COVERAGE1.LOW_DUR_1_CSV_AMT, 0)
      ELSE COALESCE(COVERAGE1.LOW_DUR_1_NSP_AMT, 0)
    END) BCVR_COV1
  , (CASE
      WHEN COALESCE(COVERAGE1.LOW_DUR_1_CSV_AMT, 0) <> 0 OR COALESCE(COVERAGE1.LOW_DUR_2_CSV_AMT, 0) <> 0
      THEN COALESCE(COVERAGE1.LOW_DUR_2_CSV_AMT, 0)
      ELSE COALESCE(COVERAGE1.LOW_DUR_2_NSP_AMT, 0)
    END) ECVR_COV1
  , INTERPOLATION_MONTHS.MONTHS_TO_NEXT_ANN
  , INTERPOLATION_MONTHS.MONTHS_YTD
  , ((CASE
      WHEN COALESCE(COVERAGE1.LOW_DUR_1_CSV_AMT, 0) <> 0 OR COALESCE(COVERAGE1.LOW_DUR_2_CSV_AMT, 0) <> 0
      THEN COALESCE(COVERAGE1.LOW_DUR_1_CSV_AMT, 0)
      ELSE COALESCE(COVERAGE1.LOW_DUR_1_NSP_AMT, 0)
    END)
    * COVERAGE1.COV_UNT_QTY * INTERPOLATION_MONTHS.MONTHS_TO_NEXT_ANN
    + (CASE
        WHEN COALESCE(COVERAGE1.LOW_DUR_1_CSV_AMT, 0) <> 0 OR COALESCE(COVERAGE1.LOW_DUR_2_CSV_AMT, 0) <> 0
        THEN COALESCE(COVERAGE1.LOW_DUR_2_CSV_AMT, 0)
        ELSE COALESCE(COVERAGE1.LOW_DUR_2_NSP_AMT, 0)
      END)
    * COVERAGE1.COV_UNT_QTY * INTERPOLATION_MONTHS.MONTHS_YTD) / 12 CV_COV1
  , MVVAL.CSV_AMT
  , TRAD_CV.INTERP_NSP
  , TRAD_CV.INTERP_CV
  , COVERAGE1.ADV_PRD_IND
  , COVERAGE1.LOW_DUR_CSV_AMT
  , COVERAGE1.LOW_DUR_1_CSV_AMT
  , COVERAGE1.LOW_DUR_NSP_AMT
  , COVERAGE1.LOW_DUR_1_NSP_AMT
  , INSURED1_INFO.FNAME
  , INSURED1_INFO.LNAME
  , VARCHAR_FORMAT(INSURED1_INFO.BIRTHDT, 'MM/DD/YYYY') BIRTHDT
  , (SELECT LISTAGG(TRIM(BNF.SPM_BNF_TYP_CD) || TRIM(BNF.SPM_BNF_SBY_CD), ', ')
            WITHIN GROUP (ORDER BY BNF.SPM_BNF_TYP_CD, BNF.SPM_BNF_SBY_CD)
       FROM DB2TAB.LH_SPM_BNF BNF
       WHERE BNF.CK_SYS_CD = POLICY1.CK_SYS_CD
         AND BNF.CK_CMP_CD = POLICY1.CK_CMP_CD
         AND BNF.TCH_POL_ID = POLICY1.TCH_POL_ID
         AND (BNF.BNF_CEA_DT IS NULL OR BNF.BNF_CEA_DT > CURRENT DATE)
      ) ActiveBenefits
  , (SELECT LISTAGG(DISTINCT_RIDERS.PLN_DES_SER_CD, ', ')
            WITHIN GROUP (ORDER BY DISTINCT_RIDERS.PLN_DES_SER_CD)
       FROM (
         SELECT DISTINCT TRIM(RIDER.PLN_DES_SER_CD) PLN_DES_SER_CD
         FROM DB2TAB.LH_COV_PHA RIDER
         WHERE RIDER.CK_SYS_CD = POLICY1.CK_SYS_CD
           AND RIDER.CK_CMP_CD = POLICY1.CK_CMP_CD
           AND RIDER.TCH_POL_ID = POLICY1.TCH_POL_ID
           AND RIDER.COV_PHA_NBR > 1
           AND TRIM(RIDER.PLN_DES_SER_CD) <> TRIM(COVERAGE1.PLN_DES_SER_CD)
           AND (RIDER.NXT_CHG_TYP_CD <> '0'
                OR (RIDER.NXT_CHG_DT IS NOT NULL
                    AND RIDER.NXT_CHG_DT > CURRENT DATE))
       ) DISTINCT_RIDERS
      ) ActiveRiders
  , FXD_PRM.POL_FEE_AMT PolFee
  , FXD_PRM.SAN_MD_FCT SemiAnnModalFactor
  , FXD_PRM.QTR_MD_FCT QtrModalFactor
  , FXD_PRM.MO_MD_FCT MoModalFactor
  , COVERAGE1.ANN_PRM_UNT_AMT PremRate
  , POLICY1.POL_PRM_AMT PolPremium
  , USERGEN.APP_RECEIVED_DATE APP_RECEIVED_DATE
  , USERGEN.SRC_CONV_EXP_DT SRC_CONV_EXP_DT
  , USERGEN.SOURCE_PLAN_CODE SOURCE_PLAN_CODE
  , USERGEN.SOURCE_PLAN_EFF_DATE SOURCE_PLAN_EFF_DATE
  , USERGEN.SOURCE_ISSUE_DATE SOURCE_ISSUE_DATE
  , USERGEN.SOURCE_FACE_AMT SOURCE_FACE_AMT
  , USERGEN.SOURCE_CNV_CREDIT_IND SOURCE_CNV_CREDIT_IND
  , USERGEN.CONV_CREDIT_AMT CONV_CREDIT_AMT
  , USERGEN.CONV_CREDIT_PERIOD CONV_CREDIT_PERIOD
  , USERGEN.CONV_TO_TRM_PERIOD CONV_TO_TRM_PERIOD
  , USERGEN.CONV_FACE_AMT CONV_FACE_AMT
FROM DB2TAB.LH_BAS_POL POLICY1
  INNER JOIN COVERAGE1
    ON POLICY1.CK_SYS_CD = COVERAGE1.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = COVERAGE1.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = COVERAGE1.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.TH_USER_GENERIC USERGEN
    ON POLICY1.CK_SYS_CD = USERGEN.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = USERGEN.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = USERGEN.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_FXD_PRM_POL FXD_PRM
    ON POLICY1.CK_SYS_CD = FXD_PRM.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = FXD_PRM.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = FXD_PRM.TCH_POL_ID
  LEFT OUTER JOIN BILLMODE_POOL
    ON POLICY1.CK_SYS_CD = BILLMODE_POOL.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = BILLMODE_POOL.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = BILLMODE_POOL.TCH_POL_ID
  LEFT OUTER JOIN COVSUMMARY
    ON COVSUMMARY.CK_SYS_CD = POLICY1.CK_SYS_CD
    AND COVSUMMARY.CK_CMP_CD = POLICY1.CK_CMP_CD
    AND COVSUMMARY.TCH_POL_ID = POLICY1.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.TH_USER_PDF UPDF
    ON POLICY1.CK_SYS_CD = UPDF.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = UPDF.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = UPDF.TCH_POL_ID
    AND UPDF.TYPE_SEQUENCE = 1
  LEFT OUTER JOIN INSURED1_INFO
    ON POLICY1.CK_SYS_CD = INSURED1_INFO.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = INSURED1_INFO.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = INSURED1_INFO.TCH_POL_ID
  INNER JOIN GRACE_TABLE
    ON POLICY1.CK_SYS_CD = GRACE_TABLE.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = GRACE_TABLE.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = GRACE_TABLE.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_TAMRA_7_PY_PER TAMRA
    ON POLICY1.CK_SYS_CD = TAMRA.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = TAMRA.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = TAMRA.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_POL_TOTALS POLICY_TOTALS
    ON POLICY1.CK_SYS_CD = POLICY_TOTALS.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = POLICY_TOTALS.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = POLICY_TOTALS.TCH_POL_ID
  LEFT OUTER JOIN LH_POL_YR_TOT_at_MaxDuration
    ON POLICY1.CK_SYS_CD = LH_POL_YR_TOT_at_MaxDuration.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = LH_POL_YR_TOT_at_MaxDuration.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = LH_POL_YR_TOT_at_MaxDuration.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_NON_TRD_POL NONTRAD
    ON POLICY1.CK_SYS_CD = NONTRAD.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = NONTRAD.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = NONTRAD.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.TH_USER_REPLACEMENT USERDEF_52R
    ON POLICY1.CK_SYS_CD = USERDEF_52R.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = USERDEF_52R.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = USERDEF_52R.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_LN_RPY_TRM SLR_BILL_CONTROL
    ON POLICY1.CK_SYS_CD = SLR_BILL_CONTROL.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = SLR_BILL_CONTROL.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = SLR_BILL_CONTROL.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.TH_BAS_POL POLICY1_MOD
    ON POLICY1.CK_SYS_CD = POLICY1_MOD.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = POLICY1_MOD.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = POLICY1_MOD.TCH_POL_ID
  LEFT OUTER JOIN TERMINATION_DATES AS TD
    ON POLICY1.CK_CMP_CD = TD.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = TD.TCH_POL_ID
    AND POLICY1.PRM_PAY_STA_REA_CD >= '97' AND POLICY1.LST_ETR_CD IN ('J', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'X')
  LEFT OUTER JOIN CONVERSION_SC SC
    ON POLICY1.CK_SYS_CD = SC.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = SC.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = SC.TCH_POL_ID
    AND SC.SC_ROW = 1
  LEFT OUTER JOIN POST_CONVERSION PC
    ON POLICY1.CK_SYS_CD = PC.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = PC.SOURCE_CMP_CODE
    AND POLICY1.CK_POLICY_NBR = PC.SOURCE_POLICY_NBR
    AND POLICY1.LST_ETR_CD = 'O'
  LEFT OUTER JOIN ALL_LOANS
    ON POLICY1.CK_SYS_CD = ALL_LOANS.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = ALL_LOANS.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = ALL_LOANS.TCH_POL_ID
  LEFT OUTER JOIN POLICYDEBT
    ON POLICY1.CK_SYS_CD = POLICYDEBT.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = POLICYDEBT.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = POLICYDEBT.TCH_POL_ID
  LEFT OUTER JOIN MVVAL
    ON POLICY1.CK_SYS_CD = MVVAL.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = MVVAL.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = MVVAL.TCH_POL_ID
  LEFT OUTER JOIN MONTHLY_DED
    ON POLICY1.CK_SYS_CD = MONTHLY_DED.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = MONTHLY_DED.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = MONTHLY_DED.TCH_POL_ID
  LEFT OUTER JOIN GLP
    ON POLICY1.CK_SYS_CD = GLP.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = GLP.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = GLP.TCH_POL_ID
  LEFT OUTER JOIN INTERPOLATION_MONTHS
    ON POLICY1.CK_SYS_CD = INTERPOLATION_MONTHS.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = INTERPOLATION_MONTHS.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = INTERPOLATION_MONTHS.TCH_POL_ID
  LEFT OUTER JOIN TRAD_CV
    ON COVERAGE1.CK_SYS_CD = TRAD_CV.CK_SYS_CD
    AND COVERAGE1.CK_CMP_CD = TRAD_CV.CK_CMP_CD
    AND COVERAGE1.TCH_POL_ID = TRAD_CV.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_COV_TARGET SHADOWAV
    ON POLICY1.CK_SYS_CD = SHADOWAV.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = SHADOWAV.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = SHADOWAV.TCH_POL_ID
    AND SHADOWAV.TAR_TYP_CD = 'XP'
  LEFT OUTER JOIN DB2TAB.LH_POL_TARGET ACCUMMTP
    ON POLICY1.CK_SYS_CD = ACCUMMTP.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = ACCUMMTP.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = ACCUMMTP.TCH_POL_ID
    AND ACCUMMTP.TAR_TYP_CD = 'MA'
  LEFT OUTER JOIN DB2TAB.LH_POL_TARGET ACCUMGLP
    ON POLICY1.CK_SYS_CD = ACCUMGLP.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = ACCUMGLP.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = ACCUMGLP.TCH_POL_ID
    AND ACCUMGLP.TAR_TYP_CD = 'TA'
  LEFT OUTER JOIN DB2TAB.LH_COM_TARGET COMMTARGET
    ON POLICY1.CK_SYS_CD = COMMTARGET.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = COMMTARGET.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = COMMTARGET.TCH_POL_ID
    AND COMMTARGET.TAR_TYP_CD = 'CT'
  LEFT OUTER JOIN DB2TAB.LH_POL_TARGET MTP
    ON POLICY1.CK_SYS_CD = MTP.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = MTP.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = MTP.TCH_POL_ID
    AND MTP.TAR_TYP_CD = 'MT'
  LEFT OUTER JOIN DB2TAB.LH_POL_TARGET NSPTARGET
    ON POLICY1.CK_SYS_CD = NSPTARGET.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = NSPTARGET.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = NSPTARGET.TCH_POL_ID
    AND NSPTARGET.TAR_TYP_CD = 'NS'
  LEFT OUTER JOIN DB2TAB.LH_POL_TARGET SHORTPAY_PRM
    ON POLICY1.CK_SYS_CD = SHORTPAY_PRM.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = SHORTPAY_PRM.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = SHORTPAY_PRM.TCH_POL_ID
    AND SHORTPAY_PRM.TAR_TYP_CD = 'VS'
  LEFT OUTER JOIN DB2TAB.TH_USER_GENERIC USERDEF_52G
    ON POLICY1.CK_SYS_CD = USERDEF_52G.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = USERDEF_52G.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = USERDEF_52G.TCH_POL_ID
  LEFT OUTER JOIN GSP
    ON POLICY1.CK_SYS_CD = GSP.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = GSP.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = GSP.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_BIL_FRM_CTL BILL_CONTROL
    ON POLICY1.CK_SYS_CD = BILL_CONTROL.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = BILL_CONTROL.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = BILL_CONTROL.TCH_POL_ID
  LEFT OUTER JOIN CHANGE_TYPE9
    ON POLICY1.CK_SYS_CD = CHANGE_TYPE9.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = CHANGE_TYPE9.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = CHANGE_TYPE9.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_FXD_PRM_POL FIXPREM
    ON POLICY1.CK_SYS_CD = FIXPREM.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = FIXPREM.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = FIXPREM.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_COV_FXD_FND_CTL FFC
    ON POLICY1.CK_SYS_CD = FFC.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = FFC.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = FFC.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.LH_COV_INS_RNL_RT COV1_RENEWALS
    ON COVERAGE1.CK_SYS_CD = COV1_RENEWALS.CK_SYS_CD
    AND COVERAGE1.CK_CMP_CD = COV1_RENEWALS.CK_CMP_CD
    AND COVERAGE1.TCH_POL_ID = COV1_RENEWALS.TCH_POL_ID
    AND COVERAGE1.COV_PHA_NBR = COV1_RENEWALS.COV_PHA_NBR
    AND COV1_RENEWALS.PRM_RT_TYP_CD = 'C'
  LEFT OUTER JOIN DB2TAB.LH_SST_XTR_CRG TABLE_RATING1
    ON COVERAGE1.CK_SYS_CD = TABLE_RATING1.CK_SYS_CD
    AND COVERAGE1.CK_CMP_CD = TABLE_RATING1.CK_CMP_CD
    AND COVERAGE1.TCH_POL_ID = TABLE_RATING1.TCH_POL_ID
    AND COVERAGE1.COV_PHA_NBR = TABLE_RATING1.COV_PHA_NBR
    AND (TABLE_RATING1.SST_XTR_TYP_CD = '0' OR TABLE_RATING1.SST_XTR_TYP_CD = '1' OR TABLE_RATING1.SST_XTR_TYP_CD = '3')
  LEFT OUTER JOIN DB2TAB.LH_SST_XTR_CRG FLAT_EXTRA1
    ON COVERAGE1.CK_SYS_CD = FLAT_EXTRA1.CK_SYS_CD
    AND COVERAGE1.CK_CMP_CD = FLAT_EXTRA1.CK_CMP_CD
    AND COVERAGE1.TCH_POL_ID = FLAT_EXTRA1.TCH_POL_ID
    AND COVERAGE1.COV_PHA_NBR = FLAT_EXTRA1.COV_PHA_NBR
    AND (FLAT_EXTRA1.SST_XTR_TYP_CD = '2' OR FLAT_EXTRA1.SST_XTR_TYP_CD = '4')
WHERE POLICY1.CK_SYS_CD = 'I'
FETCH FIRST 25 ROWS ONLY