WITH COVERAGE1 AS
  (SELECT * FROM DB2TAB.LH_COV_PHA C1 WHERE C1.COV_PHA_NBR = 1)
, TERMINATION_TRANS AS
  (SELECT FH.CK_CMP_CD, FH.TCH_POL_ID,
    FH.ENTRY_DT, FH.ASOF_DT, FH.TRANS
   FROM DB2TAB.FH_FIXED AS FH
   WHERE FH.TRANS IN ('SC', 'SI', 'SF', 'TD', 'TM', 'TN', 'TL', 'TO')
   AND FH.FCB0_REV_IND = '0'
   AND FH.FCB2_REV_APPL_IND = '0')
, PRE_TERMINATION_DATES AS
  (SELECT TT.CK_CMP_CD, TT.TCH_POL_ID,
   MAX(TT.ENTRY_DT) AS TERM_ENTRY_DT
   FROM TERMINATION_TRANS AS TT
   GROUP BY TT.CK_CMP_CD, TT.TCH_POL_ID)
, TERMINATION_ENTRY_EFFECTIVE_DATES AS
  (SELECT CK_CMP_CD, TCH_POL_ID, ENTRY_DT,
    MAX(ASOF_DT) AS TERM_EFFECTIVE_DT
   FROM TERMINATION_TRANS
   GROUP BY CK_CMP_CD, TCH_POL_ID, ENTRY_DT)
, TERMINATION_ENTRY_TRANS_TYPES AS
  (SELECT CK_CMP_CD, TCH_POL_ID, ENTRY_DT,
    MAX(CASE WHEN TRANS = 'SC' THEN 1 ELSE 0 END) AS HAS_SC,
    MAX(CASE WHEN TRANS = 'SI' THEN 1 ELSE 0 END) AS HAS_SI,
    MAX(CASE WHEN TRANS = 'SF' THEN 1 ELSE 0 END) AS HAS_SF,
    MAX(CASE WHEN TRANS = 'TD' THEN 1 ELSE 0 END) AS HAS_TD,
    MAX(CASE WHEN TRANS = 'TM' THEN 1 ELSE 0 END) AS HAS_TM,
    MAX(CASE WHEN TRANS = 'TN' THEN 1 ELSE 0 END) AS HAS_TN,
    MAX(CASE WHEN TRANS = 'TL' THEN 1 ELSE 0 END) AS HAS_TL,
    MAX(CASE WHEN TRANS = 'TO' THEN 1 ELSE 0 END) AS HAS_TO
   FROM TERMINATION_TRANS
   GROUP BY CK_CMP_CD, TCH_POL_ID, ENTRY_DT)
, TERMINATION_ENTRY_DETAILS AS
  (SELECT PTD.CK_CMP_CD, PTD.TCH_POL_ID, PTD.TERM_ENTRY_DT,
    TED.TERM_EFFECTIVE_DT,
    SUBSTR(
      CASE WHEN TTT.HAS_SC = 1 THEN ', SC' ELSE '' END ||
      CASE WHEN TTT.HAS_SI = 1 THEN ', SI' ELSE '' END ||
      CASE WHEN TTT.HAS_SF = 1 THEN ', SF' ELSE '' END ||
      CASE WHEN TTT.HAS_TD = 1 THEN ', TD' ELSE '' END ||
      CASE WHEN TTT.HAS_TM = 1 THEN ', TM' ELSE '' END ||
      CASE WHEN TTT.HAS_TN = 1 THEN ', TN' ELSE '' END ||
      CASE WHEN TTT.HAS_TL = 1 THEN ', TL' ELSE '' END ||
      CASE WHEN TTT.HAS_TO = 1 THEN ', TO' ELSE '' END,
      3) AS TERM_TRANS_TYPES
   FROM PRE_TERMINATION_DATES AS PTD
   INNER JOIN TERMINATION_ENTRY_EFFECTIVE_DATES AS TED
     ON PTD.CK_CMP_CD = TED.CK_CMP_CD
    AND PTD.TCH_POL_ID = TED.TCH_POL_ID
    AND PTD.TERM_ENTRY_DT = TED.ENTRY_DT
   INNER JOIN TERMINATION_ENTRY_TRANS_TYPES AS TTT
     ON PTD.CK_CMP_CD = TTT.CK_CMP_CD
    AND PTD.TCH_POL_ID = TTT.TCH_POL_ID
    AND PTD.TERM_ENTRY_DT = TTT.ENTRY_DT)
, TERMINATION_DATES AS
  (SELECT * FROM TERMINATION_ENTRY_DETAILS)
, TERMINATION_BOTH_DATES AS
  (SELECT CK_CMP_CD, TCH_POL_ID, MAX(ENTRY_DT) AS TERM_ENTRY_DT
   FROM TERMINATION_TRANS
   WHERE ENTRY_DT < DATE('9999-12-31')
   GROUP BY CK_CMP_CD, TCH_POL_ID)
, ALL_LOANS AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, PRF_LN_IND, LN_PRI_AMT,
    (CASE LN_ITS_AMT_TYP_CD WHEN '2' THEN POL_LN_ITS_AMT ELSE 0 END) LN_INT
  FROM DB2TAB.LH_FND_VAL_LOAN WHERE MVRY_DT = '9999-12-31'
  UNION
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID, PRF_LN_IND, LN_PRI_AMT,
    (CASE LN_ITS_AMT_TYP_CD WHEN '2' THEN POL_LN_ITS_AMT ELSE 0 END) LN_INT
  FROM DB2TAB.LH_CSH_VAL_LOAN WHERE MVRY_DT = '9999-12-31')
, POLICYDEBT AS (
  SELECT CK_SYS_CD, CK_CMP_CD, TCH_POL_ID,
    SUM(ALL_LOANS.LN_PRI_AMT) LOAN_PRINCIPLE,
    SUM(ALL_LOANS.LN_INT) LOAN_ACCRUED,
    SUM(CASE WHEN COALESCE(ALL_LOANS.PRF_LN_IND, '0') <> '1'
      THEN ALL_LOANS.LN_PRI_AMT ELSE 0 END) REG_LOAN_PRINCIPLE,
    SUM(CASE WHEN COALESCE(ALL_LOANS.PRF_LN_IND, '0') <> '1'
      THEN ALL_LOANS.LN_INT ELSE 0 END) REG_LOAN_ACCRUED,
    SUM(CASE WHEN ALL_LOANS.PRF_LN_IND = '1'
      THEN ALL_LOANS.LN_PRI_AMT ELSE 0 END) PREF_LOAN_PRINCIPLE,
    SUM(CASE WHEN ALL_LOANS.PRF_LN_IND = '1'
      THEN ALL_LOANS.LN_INT ELSE 0 END) PREF_LOAN_ACCRUED
  FROM ALL_LOANS
  GROUP BY CK_SYS_CD, CK_CMP_CD, TCH_POL_ID)

SELECT DISTINCT
  CURRENT_DATE RunDate
  , POLICY1.CK_POLICY_NBR PolicyNumber
  , POLICY1.CK_CMP_CD CompanyCode
  , POLICY1.PRM_PAY_STA_REA_CD StatusCode
  , POLICY1.SUS_CD SuspenseCode
  , SUBSTR(POLICY1.SVC_AGC_NBR, 1, 1) AgentCode
  , CASE WHEN POLICY1.POL_ISS_ST_CD = '01' THEN 'AL'
    WHEN POLICY1.POL_ISS_ST_CD = '02' THEN 'AZ'
    WHEN POLICY1.POL_ISS_ST_CD = '03' THEN 'AR'
    WHEN POLICY1.POL_ISS_ST_CD = '04' THEN 'CA'
    WHEN POLICY1.POL_ISS_ST_CD = '05' THEN 'CO'
    WHEN POLICY1.POL_ISS_ST_CD = '06' THEN 'CT'
    WHEN POLICY1.POL_ISS_ST_CD = '07' THEN 'DE'
    WHEN POLICY1.POL_ISS_ST_CD = '08' THEN 'DC'
    WHEN POLICY1.POL_ISS_ST_CD = '09' THEN 'FL'
    WHEN POLICY1.POL_ISS_ST_CD = '10' THEN 'GA'
    WHEN POLICY1.POL_ISS_ST_CD = '11' THEN 'ID'
    WHEN POLICY1.POL_ISS_ST_CD = '12' THEN 'IL'
    WHEN POLICY1.POL_ISS_ST_CD = '13' THEN 'IN'
    WHEN POLICY1.POL_ISS_ST_CD = '14' THEN 'IA'
    WHEN POLICY1.POL_ISS_ST_CD = '15' THEN 'KS'
    WHEN POLICY1.POL_ISS_ST_CD = '16' THEN 'KY'
    WHEN POLICY1.POL_ISS_ST_CD = '17' THEN 'LA'
    WHEN POLICY1.POL_ISS_ST_CD = '18' THEN 'ME'
    WHEN POLICY1.POL_ISS_ST_CD = '19' THEN 'MD'
    WHEN POLICY1.POL_ISS_ST_CD = '20' THEN 'MA'
    WHEN POLICY1.POL_ISS_ST_CD = '21' THEN 'MI'
    WHEN POLICY1.POL_ISS_ST_CD = '22' THEN 'MN'
    WHEN POLICY1.POL_ISS_ST_CD = '23' THEN 'MS'
    WHEN POLICY1.POL_ISS_ST_CD = '24' THEN 'MO'
    WHEN POLICY1.POL_ISS_ST_CD = '25' THEN 'MT'
    WHEN POLICY1.POL_ISS_ST_CD = '26' THEN 'NE'
    WHEN POLICY1.POL_ISS_ST_CD = '27' THEN 'NV'
    WHEN POLICY1.POL_ISS_ST_CD = '28' THEN 'NH'
    WHEN POLICY1.POL_ISS_ST_CD = '29' THEN 'NJ'
    WHEN POLICY1.POL_ISS_ST_CD = '30' THEN 'NM'
    WHEN POLICY1.POL_ISS_ST_CD = '31' THEN 'NY'
    WHEN POLICY1.POL_ISS_ST_CD = '32' THEN 'NC'
    WHEN POLICY1.POL_ISS_ST_CD = '33' THEN 'ND'
    WHEN POLICY1.POL_ISS_ST_CD = '34' THEN 'OH'
    WHEN POLICY1.POL_ISS_ST_CD = '35' THEN 'OK'
    WHEN POLICY1.POL_ISS_ST_CD = '36' THEN 'OR'
    WHEN POLICY1.POL_ISS_ST_CD = '37' THEN 'PA'
    WHEN POLICY1.POL_ISS_ST_CD = '38' THEN 'RI'
    WHEN POLICY1.POL_ISS_ST_CD = '39' THEN 'SC'
    WHEN POLICY1.POL_ISS_ST_CD = '40' THEN 'SD'
    WHEN POLICY1.POL_ISS_ST_CD = '41' THEN 'TN'
    WHEN POLICY1.POL_ISS_ST_CD = '42' THEN 'TX'
    WHEN POLICY1.POL_ISS_ST_CD = '43' THEN 'UT'
    WHEN POLICY1.POL_ISS_ST_CD = '44' THEN 'VT'
    WHEN POLICY1.POL_ISS_ST_CD = '45' THEN 'VA'
    WHEN POLICY1.POL_ISS_ST_CD = '46' THEN 'WA'
    WHEN POLICY1.POL_ISS_ST_CD = '47' THEN 'WV'
    WHEN POLICY1.POL_ISS_ST_CD = '48' THEN 'WI'
    WHEN POLICY1.POL_ISS_ST_CD = '49' THEN 'WY'
    WHEN POLICY1.POL_ISS_ST_CD = '50' THEN 'AK'
    WHEN POLICY1.POL_ISS_ST_CD = '51' THEN 'HI'
    WHEN POLICY1.POL_ISS_ST_CD = '52' THEN 'PR'
    ELSE POLICY1.POL_ISS_ST_CD END IssueState
  , COVERAGE1.PLN_DES_SER_CD Plancode
  , COVERAGE1.POL_FRM_NBR FormNumber
  , VARCHAR_FORMAT(COVERAGE1.ISSUE_DT, 'MM/DD/YYYY') IssueDt
  , COVERAGE1.INS_ISS_AGE IssueAge
  , USERGEN.FUZGREIN_IND RGA_Ind
  , VARCHAR_FORMAT(COALESCE(TDB.TERM_ENTRY_DT, (CASE WHEN POLICY1.PRM_PAY_STA_REA_CD >= '97' AND POLICY1.LST_ETR_CD IN ('J', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'X') THEN NULLIF(POLICY1.LST_FIN_DT, DATE('9999-12-31')) END)), 'MM/DD/YYYY') TERM_DATE_BOTH
  , CASE WHEN TDB.TERM_ENTRY_DT IS NOT NULL THEN 'Transaction (69)'
      ELSE 'Last Financial (01)' END TERM_DATE_SOURCE
  , POLICY1.LST_ETR_CD LastEntryCode
  , VARCHAR_FORMAT(POLICY1.LST_FIN_DT, 'MM/DD/YYYY') LastFinDate_Entry
  , POLICYDEBT.REG_LOAN_PRINCIPLE
  , POLICYDEBT.REG_LOAN_ACCRUED
  , POLICYDEBT.PREF_LOAN_PRINCIPLE
  , POLICYDEBT.PREF_LOAN_ACCRUED
  , (CASE
      WHEN POLICY1.LN_TYP_CD = '0' THEN 'FIX'
      WHEN POLICY1.LN_TYP_CD = '1' THEN 'FIX'
      WHEN POLICY1.LN_TYP_CD = '6' THEN 'VAR'
      WHEN POLICY1.LN_TYP_CD = '7' THEN 'VAR'
      WHEN POLICY1.LN_TYP_CD = '9' THEN 'NA'
      ELSE POLICY1.LN_TYP_CD
      END) LOAN_TYPE
  , (CASE
      WHEN POLICY1.LN_TYP_CD = '0' THEN 'ADVANCE'
      WHEN POLICY1.LN_TYP_CD = '1' THEN 'ARREARS'
      WHEN POLICY1.LN_TYP_CD = '6' THEN 'ADVANCE'
      WHEN POLICY1.LN_TYP_CD = '7' THEN 'ARREARS'
      WHEN POLICY1.LN_TYP_CD = '9' THEN 'NA'
      ELSE POLICY1.LN_TYP_CD
      END) LOAN_TIMING
  , USERGEN.SOURCE_CMP_CODE SOURCE_CMP_CODE
FROM DB2TAB.LH_BAS_POL POLICY1
  INNER JOIN COVERAGE1
    ON POLICY1.CK_SYS_CD = COVERAGE1.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = COVERAGE1.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = COVERAGE1.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.TH_USER_GENERIC USERGEN
    ON POLICY1.CK_SYS_CD = USERGEN.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = USERGEN.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = USERGEN.TCH_POL_ID
  LEFT OUTER JOIN TERMINATION_BOTH_DATES AS TDB
    ON POLICY1.CK_CMP_CD = TDB.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = TDB.TCH_POL_ID
    AND POLICY1.PRM_PAY_STA_REA_CD >= '97' AND POLICY1.LST_ETR_CD IN ('J', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'X')
  INNER JOIN ALL_LOANS
    ON POLICY1.CK_SYS_CD = ALL_LOANS.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = ALL_LOANS.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = ALL_LOANS.TCH_POL_ID
    AND ALL_LOANS.PRF_LN_IND = '1'
  INNER JOIN POLICYDEBT
    ON POLICY1.CK_SYS_CD = POLICYDEBT.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = POLICYDEBT.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = POLICYDEBT.TCH_POL_ID
WHERE POLICY1.CK_SYS_CD = 'I'
  AND COALESCE(TDB.TERM_ENTRY_DT, (CASE WHEN POLICY1.PRM_PAY_STA_REA_CD >= '97' AND POLICY1.LST_ETR_CD IN ('J', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'X') THEN NULLIF(POLICY1.LST_FIN_DT, DATE('9999-12-31')) END)) >= '2025-01-01'
  AND USERGEN.EXCH_POL_NUMBER IS NOT NULL
  AND POLICYDEBT.LOAN_PRINCIPLE >= 1.0
  AND POLICYDEBT.LOAN_ACCRUED <= 8.0
FETCH FIRST 25 ROWS ONLY