WITH COVERAGE1 AS
  (SELECT * FROM DB2TAB.LH_COV_PHA C1 WHERE C1.COV_PHA_NBR = 1)

SELECT DISTINCT
  CURRENT_DATE RunDate
  , POLICY1.CK_POLICY_NBR PolicyNumber
  , POLICY1.CK_CMP_CD CompanyCode
  , POLICY1.PRM_PAY_STA_REA_CD StatusCode
  , POLICY1.SUS_CD SuspenseCode
  , SUBSTR(POLICY1.SVC_AGC_NBR, 1, 1) AgentCode
  , CASE WHEN POLICY1.POL_ISS_ST_CD = '01' THEN 'AL'
    WHEN POLICY1.POL_ISS_ST_CD = '02' THEN 'AZ'
    WHEN POLICY1.POL_ISS_ST_CD = '03' THEN 'AR'
    WHEN POLICY1.POL_ISS_ST_CD = '04' THEN 'CA'
    WHEN POLICY1.POL_ISS_ST_CD = '05' THEN 'CO'
    WHEN POLICY1.POL_ISS_ST_CD = '06' THEN 'CT'
    WHEN POLICY1.POL_ISS_ST_CD = '07' THEN 'DE'
    WHEN POLICY1.POL_ISS_ST_CD = '08' THEN 'DC'
    WHEN POLICY1.POL_ISS_ST_CD = '09' THEN 'FL'
    WHEN POLICY1.POL_ISS_ST_CD = '10' THEN 'GA'
    WHEN POLICY1.POL_ISS_ST_CD = '11' THEN 'ID'
    WHEN POLICY1.POL_ISS_ST_CD = '12' THEN 'IL'
    WHEN POLICY1.POL_ISS_ST_CD = '13' THEN 'IN'
    WHEN POLICY1.POL_ISS_ST_CD = '14' THEN 'IA'
    WHEN POLICY1.POL_ISS_ST_CD = '15' THEN 'KS'
    WHEN POLICY1.POL_ISS_ST_CD = '16' THEN 'KY'
    WHEN POLICY1.POL_ISS_ST_CD = '17' THEN 'LA'
    WHEN POLICY1.POL_ISS_ST_CD = '18' THEN 'ME'
    WHEN POLICY1.POL_ISS_ST_CD = '19' THEN 'MD'
    WHEN POLICY1.POL_ISS_ST_CD = '20' THEN 'MA'
    WHEN POLICY1.POL_ISS_ST_CD = '21' THEN 'MI'
    WHEN POLICY1.POL_ISS_ST_CD = '22' THEN 'MN'
    WHEN POLICY1.POL_ISS_ST_CD = '23' THEN 'MS'
    WHEN POLICY1.POL_ISS_ST_CD = '24' THEN 'MO'
    WHEN POLICY1.POL_ISS_ST_CD = '25' THEN 'MT'
    WHEN POLICY1.POL_ISS_ST_CD = '26' THEN 'NE'
    WHEN POLICY1.POL_ISS_ST_CD = '27' THEN 'NV'
    WHEN POLICY1.POL_ISS_ST_CD = '28' THEN 'NH'
    WHEN POLICY1.POL_ISS_ST_CD = '29' THEN 'NJ'
    WHEN POLICY1.POL_ISS_ST_CD = '30' THEN 'NM'
    WHEN POLICY1.POL_ISS_ST_CD = '31' THEN 'NY'
    WHEN POLICY1.POL_ISS_ST_CD = '32' THEN 'NC'
    WHEN POLICY1.POL_ISS_ST_CD = '33' THEN 'ND'
    WHEN POLICY1.POL_ISS_ST_CD = '34' THEN 'OH'
    WHEN POLICY1.POL_ISS_ST_CD = '35' THEN 'OK'
    WHEN POLICY1.POL_ISS_ST_CD = '36' THEN 'OR'
    WHEN POLICY1.POL_ISS_ST_CD = '37' THEN 'PA'
    WHEN POLICY1.POL_ISS_ST_CD = '38' THEN 'RI'
    WHEN POLICY1.POL_ISS_ST_CD = '39' THEN 'SC'
    WHEN POLICY1.POL_ISS_ST_CD = '40' THEN 'SD'
    WHEN POLICY1.POL_ISS_ST_CD = '41' THEN 'TN'
    WHEN POLICY1.POL_ISS_ST_CD = '42' THEN 'TX'
    WHEN POLICY1.POL_ISS_ST_CD = '43' THEN 'UT'
    WHEN POLICY1.POL_ISS_ST_CD = '44' THEN 'VT'
    WHEN POLICY1.POL_ISS_ST_CD = '45' THEN 'VA'
    WHEN POLICY1.POL_ISS_ST_CD = '46' THEN 'WA'
    WHEN POLICY1.POL_ISS_ST_CD = '47' THEN 'WV'
    WHEN POLICY1.POL_ISS_ST_CD = '48' THEN 'WI'
    WHEN POLICY1.POL_ISS_ST_CD = '49' THEN 'WY'
    WHEN POLICY1.POL_ISS_ST_CD = '50' THEN 'AK'
    WHEN POLICY1.POL_ISS_ST_CD = '51' THEN 'HI'
    WHEN POLICY1.POL_ISS_ST_CD = '52' THEN 'PR'
    ELSE POLICY1.POL_ISS_ST_CD END IssueState
  , COVERAGE1.PLN_DES_SER_CD Plancode
  , COVERAGE1.POL_FRM_NBR FormNumber
  , VARCHAR_FORMAT(COVERAGE1.ISSUE_DT, 'MM/DD/YYYY') IssueDt
  , COVERAGE1.INS_ISS_AGE IssueAge
  , USERGEN.FUZGREIN_IND RGA_Ind
  , COVERAGE1.DIV_PTP_TYP_CD ParticipationCode
  , (CASE WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H') THEN 'Participating' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) IN ('9') THEN 'Participating but divs are paid up' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) IN ('', '0', '1', '2', '3', '4', '5', '6', '7', '8') THEN 'Nonparticipating' ELSE 'Unknown' END) Participation
  , (CASE WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = '' THEN 'Nonparticipating' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = '0' THEN 'Nonparticipating' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = '1' THEN 'Nonparticipating' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = '2' THEN 'Nonparticipating with coupons' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = '3' THEN 'Nonparticipating with pure endowments' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = '4' THEN 'Nonparticipating with guaranteed annual endowments' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = '5' THEN 'Nonparticipating with other forms' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = '6' THEN 'Nonparticipating with other forms' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = '7' THEN 'Nonparticipating with other forms' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = '8' THEN 'Nonparticipating with other forms' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = '9' THEN 'Participating but divs are paid up' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = 'A' THEN 'Participating (dividends)' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = 'B' THEN 'Participating with coupons' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = 'C' THEN 'Participating with pure endowments' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = 'D' THEN 'Participating with guaranteed annual endowments' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = 'E' THEN 'Participating with other forms' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = 'F' THEN 'Participating with other forms' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = 'G' THEN 'Participating with other forms' WHEN TRIM(COVERAGE1.DIV_PTP_TYP_CD) = 'H' THEN 'Participating with other forms' ELSE 'Unknown' END) ParticipationType
  , COVERAGE1.LOW_DUR_1_CSV_AMT CVRate1
  , COVERAGE1.LOW_DUR_2_CSV_AMT CVRate2
FROM DB2TAB.LH_BAS_POL POLICY1
  INNER JOIN COVERAGE1
    ON POLICY1.CK_SYS_CD = COVERAGE1.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = COVERAGE1.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = COVERAGE1.TCH_POL_ID
  LEFT OUTER JOIN DB2TAB.TH_USER_GENERIC USERGEN
    ON POLICY1.CK_SYS_CD = USERGEN.CK_SYS_CD
    AND POLICY1.CK_CMP_CD = USERGEN.CK_CMP_CD
    AND POLICY1.TCH_POL_ID = USERGEN.TCH_POL_ID
WHERE POLICY1.CK_SYS_CD = 'I'
  AND POLICY1.PRI_DIV_OPT_CD IN ('0')
  AND TRIM(COVERAGE1.DIV_PTP_TYP_CD) IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H')
  AND (COVERAGE1.LOW_DUR_1_CSV_AMT > 0 OR COVERAGE1.LOW_DUR_2_CSV_AMT > 0)
FETCH FIRST 25 ROWS ONLY