import os

filepath = os.path.join('suiteview', 'ratemanager', 'exporter.py')

lines = []
lines.append('"""')
lines.append('IAF Rate File Excel Exporter')
lines.append('')
lines.append('Builds a structured .xlsx workbook from parsed IAF data.')
lines.append('Ports the VBA CPDReady() logic from ProgressBar.frm.')
lines.append('"""')
lines.append('')
lines.append('import os')
lines.append('from collections import OrderedDict')
lines.append('from typing import List, Optional, Callable')
lines.append('from openpyxl import Workbook')
lines.append('from openpyxl.styles import Font, Alignment, PatternFill, Border, Side')
lines.append('from openpyxl.utils import get_column_letter')
lines.append('')
lines.append('from suiteview.ratemanager.parser import ParseResult, ProductInfo, AdvProductInfo, RateRecord')
lines.append('')
lines.append('')
lines.append('# ---------------------------------------------------------------------------')
lines.append('# Helpers')
lines.append('# ---------------------------------------------------------------------------')
lines.append('')
lines.append('def _clean_plan_option(raw: str) -> str:')
lines.append('    """Strip leading/trailing \'*\' from plan option (matches VBA logic)."""')
lines.append('    result = raw')
lines.append("    if result and result[0] == '*':")
lines.append('        result = result[1:]')
lines.append("    if result and result[-1] == '*':")
lines.append('        result = result[:-1]')
lines.append('    if not result:')
lines.append("        result = ''")
lines.append('    return result')
lines.append('')
lines.append('')
lines.append('def _format_date_for_tab(date_str: str) -> str:')
lines.append('    """Convert MM/DD/YYYY to MM-DD-YYYY for sheet tab names."""')
lines.append("    return date_str.replace('/', '-')")
lines.append('')
lines.append('')
lines.append('def _make_sheet_name(rate_type, scale_start, plan_option, is_select):')
lines.append('    """Build the worksheet tab name matching VBA naming convention."""')
lines.append('    opt = _clean_plan_option(plan_option)')
lines.append('    date_part = _format_date_for_tab(scale_start)')
lines.append("    name = f'{rate_type} - {date_part} {opt}'")
lines.append('    if is_select:')
lines.append("        name += ' Select'")
lines.append('    return name[:31]')
lines.append('')
lines.append('')
lines.append('def _safe_num(val):')
lines.append('    """Try to convert to int or float for Excel cells."""')
lines.append('    if isinstance(val, (int, float)):')
lines.append('        return val')
lines.append('    try:')
lines.append("        v = val.strip() if isinstance(val, str) else str(val)")
lines.append("        if '.' in v:")
lines.append('            return float(v)')
lines.append('        return int(v)')
lines.append('    except (ValueError, TypeError):')
lines.append('        return val')
lines.append('')
lines.append('')
lines.append('# ---------------------------------------------------------------------------')
lines.append('# Styling')
lines.append('# ---------------------------------------------------------------------------')
lines.append('')
lines.append("_HEADER_FONT = Font(name='Segoe UI', bold=True, size=10)")
lines.append("_SECTION_FONT = Font(name='Segoe UI', bold=True, size=11, color='1F4E79')")
lines.append('')
lines.append('')

with open(filepath, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'Part 1 written: {len(lines)} lines')
