"""Generate ``suiteview/audit/db2_table_fields.py`` from the translation workbook.

The Audit tool's Custom Display tab lets users add any column of a supported
CyberLife DB2 table to the generated SELECT.  The field catalog comes from the
``Translation`` sheet of ``docs/COBOLDB2translation.xls``: every row whose
``Table`` is one of :data:`CUSTOM_DISPLAY_SEGMENTS` contributes its
``Field Name`` (first occurrence wins, in sheet order) and ``Translation``
description.  :data:`WORKBOOK_NOT_LIVE` / :data:`LIVE_ONLY_COLUMNS` reconcile
the workbook with the live DB2 catalog so every offered field really exists.

Usage:
    venv\\Scripts\\python.exe tools\\audit\\build_db2_table_fields.py
    venv\\Scripts\\python.exe tools\\audit\\build_db2_table_fields.py --check
    venv\\Scripts\\python.exe tools\\audit\\build_db2_table_fields.py --verify-live CKPR
    venv\\Scripts\\python.exe tools\\audit\\build_db2_table_fields.py --refresh-kinds CKPR

``--check`` exits non-zero when the committed module is stale.
``--verify-live`` runs zero-row ``SELECT * ... WHERE 1 = 0`` queries (no policy
data is read) and fails when the catalog and live columns differ, the policy
key is missing, a table has LOB columns (unusable in ``SELECT DISTINCT``), or
a column kind differs from ``custom_display_column_kinds.json``.
``--refresh-kinds`` rewrites that snapshot from the same zero-row queries; run
it (then regenerate) after adding a table.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

XLS = ROOT / "docs" / "COBOLDB2translation.xls"
OUT = ROOT / "suiteview" / "audit" / "db2_table_fields.py"

# (policy-record segment, DB2 table) in the order shown in the Table dropdown.
CUSTOM_DISPLAY_SEGMENTS: tuple[tuple[str, str], ...] = (
    ("01", "LH_BAS_POL"),
    ("01", "TH_BAS_POL"),
    ("02", "LH_COV_PHA"),
    ("02", "TH_COV_PHA"),
    ("35", "LH_SPE_FQY_PRM"),
    ("66", "LH_NON_TRD_POL"),
    ("66", "TH_NON_TRD_POL"),
    ("72", "LH_CTT_NOTE"),
)

# The workbook disagrees with the live DB2 catalog for a few columns.  Verified
# identical in CKPR, CKAS, CKCS and CKSR on 2026-09-29 with --verify-live.
# Workbook names that do not exist live are dropped (selecting them would fail
# the query); live-only columns are appended with no description.
WORKBOOK_NOT_LIVE: dict[str, frozenset[str]] = {
    "LH_COV_PHA": frozenset({"DTH_BEN_ADJ_IND"}),
    "LH_NON_TRD_POL": frozenset({"PLVL_GAV_RULE"}),
}
LIVE_ONLY_COLUMNS: dict[str, tuple[str, ...]] = {
    "LH_BAS_POL": ("TCH_POL_ID", "NEWBADV_IND", "LOANPAY_IND", "ODS_SHOW_SGNL",
                   "PRODUCT_INFO", "ODS_PREREG_SGNL"),
    "TH_BAS_POL": ("AML_MONITOR_IND", "OVERLOAN_IND", "DUEDAY_RULES_IND", "FRAUD_IND",
                   "CONVCRED_APPLY_IND"),
    "LH_COV_PHA": ("DEATH_BEN_ADJ_IND", "PLAN_DESCRIPTION"),
    "TH_COV_PHA": ("OPT_EXER_IND", "PRM_TBL_CEA_RLE"),
    "LH_NON_TRD_POL": ("GAV_RULE_CODE",),
    "TH_NON_TRD_POL": ("SAFETY_NET_CALC", "SURR_RATE_INT", "SAFETY_NET_REIN_RULE"),
}

# Snapshot of live column kinds (text / integer / decimal / date / time /
# timestamp) written by --refresh-kinds; drives type-aware Exact/Range criteria.
KINDS_JSON = Path(__file__).with_name("custom_display_column_kinds.json")
_KIND_BY_TYPE = {
    "CHAR": "text", "VARCHAR": "text", "LONGVAR": "text", "GRAPHIC": "text", "VARG": "text",
    "SMALLINT": "integer", "INTEGER": "integer", "BIGINT": "integer",
    "DECIMAL": "decimal", "FLOAT": "decimal", "DECFLOAT": "decimal",
    "DATE": "date", "TIME": "time", "TIMESTMP": "timestamp",
}

_HEADER = '''"""
DB2 table field catalog for the Cyberlife Custom Display tab.

Generated by tools/audit/build_db2_table_fields.py from
docs/COBOLDB2translation.xls (Translation sheet), reconciled with the live
DB2 catalog -- do not edit by hand.
Maps each supported DB2 table to an ordered list of (field, description)
pairs.  Used to populate the Table/Field list boxes so a user can add
specific columns to the generated SELECT.  FIELD_KINDS gives each column's
live DB2 kind (text / integer / decimal / date / time / timestamp) so
criteria values are compared with the right SQL literal type.
"""
from __future__ import annotations

'''


def table_label(segment: str, table: str) -> str:
    return f"Seg {segment} - {table}"


def read_table_fields() -> dict[str, list[tuple[str, str]]]:
    import xlrd

    wanted = {table for _seg, table in CUSTOM_DISPLAY_SEGMENTS}
    sheet = xlrd.open_workbook(str(XLS)).sheet_by_name("Translation")
    headers = [str(sheet.cell_value(0, c)).strip() for c in range(sheet.ncols)]
    col = {name: headers.index(name) for name in ("Table", "Field Name", "Translation")}
    fields: dict[str, list[tuple[str, str]]] = {table: [] for table in wanted}
    seen: dict[str, set[str]] = {table: set() for table in wanted}
    for r in range(1, sheet.nrows):
        table = str(sheet.cell_value(r, col["Table"])).strip()
        field = str(sheet.cell_value(r, col["Field Name"])).strip()
        if table not in wanted or not field or field in seen[table]:
            continue
        seen[table].add(field)
        if field in WORKBOOK_NOT_LIVE.get(table, ()):
            continue
        fields[table].append((field, str(sheet.cell_value(r, col["Translation"])).strip()))
    missing = [table for table in wanted if not fields[table]]
    if missing:
        raise RuntimeError(f"No workbook fields for: {', '.join(sorted(missing))}")
    for table, extra in LIVE_ONLY_COLUMNS.items():
        duplicated = seen[table].intersection(extra)
        if duplicated:
            raise RuntimeError(f"{table}: now in workbook, drop from LIVE_ONLY_COLUMNS: {sorted(duplicated)}")
        fields[table].extend((field, "") for field in extra)
    return fields


def read_kinds() -> dict[str, dict[str, str]]:
    with open(KINDS_JSON, encoding="utf-8") as fh:
        return json.load(fh)


def render(fields: dict[str, list[tuple[str, str]]],
           kinds: dict[str, dict[str, str]] | None = None) -> str:
    kinds = read_kinds() if kinds is None else kinds
    lines = [_HEADER.rstrip("\n"), "",
             "# table label shown in the UI -> DB2 table name",
             "CUSTOM_DISPLAY_TABLES = {"]
    for segment, table in CUSTOM_DISPLAY_SEGMENTS:
        lines.append(f"    {table_label(segment, table)!r}: {table!r},")
    lines += ["}", "", "# DB2 table name -> list of (field_name, description)", "TABLE_FIELDS = {"]
    for _segment, table in CUSTOM_DISPLAY_SEGMENTS:
        lines.append(f"    {table!r}: [")
        for field, desc in fields[table]:
            lines.append(f"        ({field!r}, {desc!r}),")
        lines.append("    ],")
    lines += ["}", "", "# DB2 table name -> {field_name: kind}", "FIELD_KINDS = {"]
    for _segment, table in CUSTOM_DISPLAY_SEGMENTS:
        table_kinds = kinds.get(table, {})
        unknown = [field for field, _desc in fields[table] if field not in table_kinds]
        if unknown:
            raise RuntimeError(f"{table}: no kind for {unknown}; run --refresh-kinds")
        lines.append(f"    {table!r}: {{")
        for field, _desc in fields[table]:
            lines.append(f"        {field!r}: {table_kinds[field]!r},")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _describe_live(region: str):
    """Yield (table, {COLUMN: SYSIBM.SYSCOLUMNS.COLTYPE}) or (table, error text).

    Uses a zero-row query to prove the table is selectable, then the DB2
    catalog for true column types (the DV driver's ODBC description and
    catalog functions report DATE columns as character).
    """
    from suiteview.audit.sql_helpers import esc
    from suiteview.core.db2_connection import DB2Connection, _extract_odbc_message
    from suiteview.core.db2_constants import DEFAULT_SCHEMA, REGION_SCHEMA_MAP

    if os.environ.get("SUITEVIEW_LOCAL_DATA") == "1":
        raise RuntimeError("Live schema verification requires SUITEVIEW_LOCAL_DATA disabled.")
    schema = REGION_SCHEMA_MAP.get(region.upper(), DEFAULT_SCHEMA)
    db = DB2Connection(region)
    try:
        cursor = db.connect().cursor()
        for _segment, table in CUSTOM_DISPLAY_SEGMENTS:
            try:
                cursor.execute(f"SELECT * FROM {schema}.{table} WHERE 1 = 0")
                selectable = [d[0].upper() for d in cursor.description]
                # Names come from the constant table list; the DV driver rejects
                # bound parameters on catalog queries.
                cursor.execute(
                    "SELECT NAME, COLTYPE FROM SYSIBM.SYSCOLUMNS"
                    f" WHERE TBCREATOR = '{esc(schema)}' AND TBNAME = '{esc(table)}'")
                types = {str(name).strip().upper(): str(coltype).strip().upper()
                         for name, coltype in cursor.fetchall()}
            except Exception as exc:  # report and keep checking other tables
                yield table, _extract_odbc_message(exc)
                continue
            yield table, {name: types.get(name, "?") for name in selectable}
    finally:
        db.close()


def _kind(column: str, type_name: str) -> str:
    if type_name not in _KIND_BY_TYPE:
        raise RuntimeError(f"Unmapped DB2 column type {type_name!r} for {column}")
    return _KIND_BY_TYPE[type_name]


def refresh_kinds(region: str) -> int:
    kinds: dict[str, dict[str, str]] = {}
    for table, live in _describe_live(region):
        if isinstance(live, str):
            print(f"{table}: ERROR {live}")
            return 1
        kinds[table] = {name: _kind(name, type_name) for name, type_name in sorted(live.items())}
    with open(KINDS_JSON, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(kinds, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print(f"wrote {KINDS_JSON.relative_to(ROOT)} ({sum(len(v) for v in kinds.values())} columns)")
    return 0


def verify_live(region: str, fields: dict[str, list[tuple[str, str]]]) -> int:
    snapshot = read_kinds()
    problems = 0
    for table, live in _describe_live(region):
        if isinstance(live, str):
            problems += 1
            print(f"{table}: ERROR {live}")
            continue
        catalog = {f for f, _ in fields[table]}
        missing = [f for f, _ in fields[table] if f not in live]
        extra = [name for name in live if name not in catalog]
        lobs = [name for name, type_name in live.items()
                if type_name.endswith("LOB") or type_name not in _KIND_BY_TYPE]
        kind_drift = [name for name, type_name in live.items()
                      if type_name in _KIND_BY_TYPE
                      and snapshot.get(table, {}).get(name) != _KIND_BY_TYPE[type_name]]
        keys = {"CK_SYS_CD", "CK_CMP_CD", "TCH_POL_ID"} <= set(live)
        print(f"{table}: live={len(live)} catalog={len(fields[table])} "
              f"keys={'ok' if keys else 'MISSING'} cov_pha_nbr={'COV_PHA_NBR' in live}")
        if missing:
            print(f"  catalog fields missing live: {', '.join(missing)}")
        if extra:
            print(f"  live columns not in catalog: {', '.join(extra)}")
        if lobs:
            print(f"  LOB/unmapped columns: {', '.join(lobs)}")
        if kind_drift:
            print(f"  column kinds differ from snapshot: {', '.join(kind_drift)}")
        problems += bool(missing) + bool(extra) + bool(lobs) + bool(kind_drift) + (not keys)
    return 1 if problems else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if the module is stale")
    parser.add_argument("--verify-live", metavar="REGION", help="check tables against live DB2")
    parser.add_argument("--refresh-kinds", metavar="REGION",
                        help="rewrite the column-kind snapshot from live DB2")
    args = parser.parse_args()
    if args.refresh_kinds:
        return refresh_kinds(args.refresh_kinds)
    fields = read_table_fields()
    if args.verify_live:
        return verify_live(args.verify_live, fields)
    text = render(fields)
    current = OUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUT.exists() else ""
    if args.check:
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is stale; rerun without --check")
            return 1
        print("up to date")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({sum(len(v) for v in fields.values())} fields)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
