"""
DB2 table field catalog for the Cyberlife Custom Display tab.

Auto-generated from docs/COBOLDB2translation.xls (Translation sheet).
Maps each supported DB2 table to an ordered list of (field, description)
pairs.  Used to populate the Table/Field list boxes so a user can add
specific columns to the generated SELECT.
"""
from __future__ import annotations

# table label shown in the UI -> DB2 table name
CUSTOM_DISPLAY_TABLES = {
    'Policy (LH_BAS_POL)': 'LH_BAS_POL',
    'Policy Adv (TH_BAS_POL)': 'TH_BAS_POL',
    'Coverage (LH_COV_PHA)': 'LH_COV_PHA',
    'Coverage Adv (TH_COV_PHA)': 'TH_COV_PHA',
}

# DB2 table name -> list of (field_name, description)
TABLE_FIELDS = {
    'LH_BAS_POL': [
        ('ACY_POL_CD', 'Record Status'),
        ('ADM_CMP_CD', 'Administrative Company Code'),
        ('APL_LIM_CD', 'APL Stop Code'),
        ('APL_PRC_CD', 'Automatic Premium Loan Code'),
        ('APP_WRT_DT', 'Application Date'),
        ('ASN_IND_CD', 'Restrict Code Assignment'),
        ('ATM_FLE_MNT_IND', 'Automatic Change Indicator'),
        ('BIL_CRY_CD', 'Billing Currency'),
        ('BIL_DAY_NBR', 'Billing Day'),
        ('BIL_DAY_USE_CD', 'Billing Use Code'),
        ('BIL_ERT_TYP_CD', 'Billing Kind'),
        ('BIL_FRM_CD', 'Billing Form'),
        ('BIL_LGG_CD', 'Billing Language'),
        ('CK_CMP_CD', 'Company Code (Primary Key)'),
        ('CK_POLICY_NBR', 'Policy Number'),
        ('CK_SYS_CD', 'System Code (Primary Key)'),
        ('CLC_GDL_PRM_IND', 'TEFRA/DEFRA guideline indicator (0=not under, 1=under)'),
        ('COM_CHARGEBACK_CD', 'Commission Chargeback Code'),
        ('DIV_2ND_OPT_CD', 'Dividend Secondary'),
        ('DIV_ACY_CLC_DT', 'Next Dividend or Automatic Transaction Activity Date'),
        ('DTH_BNF_CD', 'Death Benefit Indicator'),
        ('EIL_IND', 'EIL Indicator'),
        ('FIN_CMP_CD', 'Financial Company Code'),
        ('FST_SKIP_MO_NBR', 'Nonstandard Mode Skip Month'),
        ('FXD_PRM_IND', 'Flexible Premium Indicator (0=Flexible, 1=Fixed)'),
        ('GRP_HST_IND', 'Group History Indicator'),
        ('ICL_IN_POL_CNT_IND', 'Bit 1'),
        ('IDT_PRM_IND', 'Indeterminate Premium Indicator'),
        ('INT_MLV_NBR', 'Initial Monthliversary'),
        ('ISS_CMP_CD', 'Issue Company Code'),
        ('ISS_CTR_CD', 'Issue Country'),
        ('LN_PLN_ITS_RT', 'Loan Interest Rate'),
        ('LN_TYP_CD', 'Loan Interest Type Code'),
        ('LST_ETR_CD', 'Last Entry Code'),
        ('LST_FIN_DT', 'Last Financial Date'),
        ('LST_POL_CHG_DT', 'Other Date'),
        ('MEC_STATUS_CD', 'MEC Indicator - Policy Level'),
        ('MO_TO_SKIP_NBR', 'Nonstandard Mode Number of Months to Skip'),
        ('NFO_OPT_TYP_CD', 'Nonforfeiture Option'),
        ('NON_TRD_POL_IND', 'Traditional Policy Indicator (0=TRAD, 1=Advanced)'),
        ('NSD_MD_CD', 'Nonstandard Modes'),
        ('NXT_BIL_DT', 'Next Bill Date'),
        ('NXT_MVRY_PRC_DT', 'Next Monthliversary Date'),
        ('NXT_SCH_NOT_DT', 'Next Scheduled Notification Date'),
        ('NXT_SCH_STT_DT', 'Next Scheduled Statement Date'),
        ('NXT_YR_END_PRC_DT', 'Next Year-End Date'),
        ('OFL_PRC_REQ_DT', 'Next Offline Processing Date'),
        ('OGN_ETR_CD', 'Original Entry Code'),
        ('OGN_EXP_DT', 'Next Potential Termination Event Date'),
        ('OL_FLE_MNT_IND', 'Online Requested Change Indicator'),
        ('OTH_FRM_2ND_OPT_CD', 'Other Dividend Secondary'),
        ('PAY_CTR_CD', 'Resident Country'),
        ('PAY_TAX_DST_CD', 'Resident Area'),
        ('PEN_TST_CD', 'Pension'),
        ('PLN_TMN_DT', 'Next Potential Termination Event Date'),
        ('PMT_FQY_PER', 'Billing Mode'),
        ('PND_STA_REA_CD', 'Pending Status'),
        ('POL_1035_XCG_IND', '1035 Exchange Indicator'),
        ('POL_CHG_RPT_TYP_CD', 'Change Pending Code (Reserved)'),
        ('POL_CTT_TYP_CD', 'Policy Type'),
        ('POL_ISS_ST_CD', 'Issue State'),
        ('POL_PRM_AMT', 'Mode Premium'),
        ('PRI_DIV_OPT_CD', 'Dividend Option'),
        ('PRI_OTH_FRM_OPT_CD', 'Other Dividend Option'),
        ('PRM_BILL_TO_DT', 'Billed-To Date'),
        ('PRM_COM_MTH_CD', 'Commission Premium Method'),
        ('PRM_DSC_CD', 'Premium Discount'),
        ('PRM_PAID_TO_DT', 'Paid-To Date'),
        ('PRM_PAY_ST_CD', 'Resident State'),
        ('PRM_PAY_STA_REA_CD', 'Billing Status'),
        ('PW_OPT_CD', 'Premium Waiver Option'),
        ('REINSURED_CD', 'Reinsured Code'),
        ('RES_CPE_CLC_IND', 'Bit 6'),
        ('RTT_1_CD', 'Restriction Code'),
        ('SPE_BIL_HDL_CD', 'Handling'),
        ('STA_CHG_IND', 'Online Status Change Indicator'),
        ('STD_PRM_PRC_IND', 'APL Mode Premium Recalculation Indicator'),
        ('SUS_CD', 'Suspend Billing Code'),
        ('SVC_AGC_NBR', 'Branch or Agency'),
        ('SVC_AGT_NBR', 'Agent'),
        ('VAR_FND_ELG_IND', 'Bit 4'),
        ('ADVANCE_IND', ''),
        ('LST_BIL_ERT_DT', ''),
        ('TRD_POL_ANU_IND', ''),
        ('TAMRA_GDF_IND', ''),
        ('TFDF_GDL_IND', ''),
        ('CB_1035_IND', ''),
        ('CB_1035_OVER_IND', ''),
        ('LST_ANV_DT', ''),
        ('NXT_IND_INC_DT', ''),
        ('LST_ACT_TRS_DT', ''),
        ('SPEC_CASE_IND', ''),
        ('USR_RES_CD', ''),
    ],
    'TH_BAS_POL': [
        ('ARCH_RESTR_CODE', 'Archived Restriction Code'),
        ('BILL_DAY_1', 'Bill Day 1'),
        ('BILL_DAY_2', 'Bill Day 2'),
        ('CK_CMP_CD', 'Company Code (Primary Key)'),
        ('CK_SYS_CD', 'System Code (Primary Key)'),
        ('FORCED_PREM_IND', 'Forced Premium Indicator'),
        ('LUS_IND', 'LUS Indicator'),
        ('REIN_MAX_XEEDED', 'Maximum Indicator'),
        ('REVIEW_NEED_IND', 'Review Needed Indicator'),
        ('TCH_POL_ID', 'Policy Number + Code (Primary Key)'),
        ('BLDY_KEYWORD_IND', ''),
        ('LOAN_INT_SEL', ''),
    ],
    'LH_COV_PHA': [
        ('ADJ_ETI_CD', 'Adjust (Nonforfeiture Rule)'),
        ('ADV_PRD_IND', 'Advanced Product Indicator'),
        ('AGE_CLC_RLE_CD', 'Age Calculation Rule'),
        ('AGE_SRC_CD', 'Age Admitted Code'),
        ('AGE_USE_CD', 'Age Use Code'),
        ('AGT_COM_PHA_NBR', 'Agent Phase Code'),
        ('AH_ACC_BNF_PER_CD', 'Further Description - Accident'),
        ('AH_ACC_ELM_PER_CD', 'Elimination Period - Accident'),
        ('AH_DED_AMT_CD', 'A&H Deductible Amount'),
        ('AH_SIC_BNF_PER_CD', 'Further Description - Sickness'),
        ('AH_SIC_ELM_PER_CD', 'Elimination Period - Sickness'),
        ('ANN_PRM_INP_IND', 'Forced Premium Flag'),
        ('ANN_PRM_UNT_AMT', 'Annual Premium Per Unit'),
        ('ANU_AT_ISS_DUR_NBR', 'Annuity Durations Guaranteed at Issue'),
        ('ANU_PUR_VAL_RLE_CD', 'Annuity Purchase Value Rule'),
        ('ANU_QFY_TYP_CD', 'Annuity Qualification Type'),
        ('ANU_SET_OPT_CD', 'Annuity Settlement Option'),
        ('AP_TRM_RID_IND', 'Bit 0'),
        ('ATM_ICE_IND', 'Auto Increase Flag'),
        ('BAN_STRUCTURE_CD', 'Band Structure Code'),
        ('BAS_COV_IND', 'Base Coverage'),
        ('BLIR_PUA_CHG_IND', 'Ceased Due to PUA Dividend Option Change from PUA'),
        ('CEA_DT_INP_IND', 'Cease Date Indicator'),
        ('CEA_REA_CD', 'Cease Reason Code'),
        ('CK_CMP_CD', 'Company Code (Primary Key)'),
        ('CK_SYS_CD', 'System Code (Primary Key)'),
        ('COM_BAS_CD', 'Commission Basic'),
        ('COM_PHA_INP_IND', 'Input Commission Phase Flag'),
        ('COM_PLN_GRP_CD', 'Commission Group Code'),
        ('COM_PLN_VTN_CD', 'Commission Variation'),
        ('COM_RLE_CD', 'Commision Rule'),
        ('COV_AMT_REQ_IND', 'Coverage Amount Request Flag'),
        ('COV_MED_CD', 'Medical Code'),
        ('COV_MT_EXP_DT', 'Mature/Expire Date'),
        ('COV_NFO_CD', 'Nonforfeiture Option'),
        ('COV_PHA_NBR', 'Coverage Phase Control Code'),
        ('COV_REETR_IND', 'Reentry Flag'),
        ('COV_RVL_RQR_IND', 'Coverage Revalidation Required Flag'),
        ('COV_UNT_QTY', 'Number of Units'),
        ('COV_VPU_AMT', 'Value-Per-Unit'),
        ('CPI_IFT_FCT', 'CPI Inflation Factor'),
        ('CSH_VAL_YR', 'Cash Value Year'),
        ('DCA_FCA_IND', 'Coverage Decrease Indicator'),
        ('DCA_TRM_ITS_RT', 'Decreasing Term Interest Rate'),
        ('DCA_TRM_LVL_YR_DUR', 'Decreasing Term Level Year'),
        ('DCA_TRM_VPU_CUM_CD', 'Decreasing Term Value-Per-Unit Calculation Technique'),
        ('DFI_CD', 'Deficient Code'),
        ('DIV_PTP_TYP_CD', 'Requested Dividend Option'),
        ('DTH_BNF_EFF_AGE', 'Death Benefit Effective Age'),
        ('EI_BNF_CD', 'EI Benefit (Nonforfeiture Rule)'),
        ('EI_INT_AMT_CD', 'EI Initial Amount (Nonforfeiture Rule)'),
        ('EIL_IND', 'EIL Coverage Code Indicator'),
        ('EIL_POL_FEE_IND', 'EIL Policy Fee Coverage'),
        ('ETR_SRC_CD', 'Entry Source'),
        ('FOC_1035_XCG_IND', 'Forced 1035 Exchange Indicator'),
        ('FOC_BAN_IND', 'Forced Band Code Indicator'),
        ('FOC_UNISEX_OVR_IND', 'Unisex Override Indicator'),
        ('FTD_RID_AT_RSK_AMT', 'Rider Net Amount at Risk'),
        ('FTD_RID_CDR_AMT', 'Rider Corridor Amount'),
        ('FTD_RID_PLN_OPT_CD', 'Rider Plan Option'),
        ('FXD_ANU_BIL_AMT', 'Fixed Value Annuity Billing Amount'),
        ('GUA_ISS_IND', 'Guaranteed Issue Indicator'),
        ('GUA_PTP_APP_OPT_CD', 'Guaranteed Participation Option'),
        ('IDT_PRM_GUA_PER', 'Indeterminate Premium Guaranteed Period'),
        ('IF_POL_IND', 'Inforce Coverage Indicator'),
        ('INS_CLS_CD', 'Class Code (part of plancode)'),
        ('INS_ISS_AGE', 'Issue Age'),
        ('INS_SEX_CD', 'Sex Code'),
        ('INT_RNL_PER', 'Initial Renewal Period'),
        ('INT_TRM_ALW_IND', 'Initial Term Flag'),
        ('ISSUE_DT', 'Issue Date'),
        ('IVD_COV_IND', 'Invalid Coverage Flag'),
        ('JNT_ISU_ISS_AGE', 'Joint Issue Age'),
        ('JNT_ISU_MTL_TBL_CD', 'Joint Mortality Table'),
        ('LIF_FURTHER_DES_CD', 'Further Description - Accident and Sickness'),
        ('LIF_PLN_SUB_SRE_CD', 'Subseries Code (part of plancode)'),
        ('LIVES_COV_CD', 'Lives'),
        ('LNG_TRM_CLM_TYP_CD', 'Long Term Care Claim Type'),
        ('LOW_DUR_1_CSV_AMT', 'Low Duration Cash Value'),
        ('LOW_DUR_1_NSP_AMT', 'Low Duration Net Single Premium Amount'),
        ('LOW_DUR_2_CSV_AMT', 'Low Duration Cash Value'),
        ('LOW_DUR_2_NSP_AMT', 'Low Duration Net Single Premium Amount'),
        ('LOW_DUR_3_CSV_AMT', 'Low Duration Cash Value'),
        ('LOW_DUR_CSV_AMT', 'Low Duration Cash Value'),
        ('LOW_DUR_NSP_AMT', 'Low Duration Net Single Premium Amount'),
        ('LOW_DUR_PER', 'Low Duration'),
        ('MAJ_LIN_OF_BUS_CD', 'Major Line of Insurance'),
        ('MDRT_CD', 'Production Million Dollar Round Table'),
        ('MEC_STA_CD', 'MEC Indicator'),
        ('MTL_FCT_TBL_CD', 'Mortality Table'),
        ('MTL_FUN_CD', 'Function (Mortality function used)'),
        ('NBR_OF_LIVES_CD', 'Lives'),
        ('NSP_EI_TBL_CD', 'EI Table'),
        ('NSP_ITS_RT', 'Interest Rate (used in nonforfeiture benefits)'),
        ('NSP_RPU_TBL_CD', 'RPU Table'),
        ('NXT_CHG_DT', 'Next Change Date'),
        ('NXT_CHG_TYP_CD', 'Next Change Type'),
        ('OGN_SPC_UNT_QTY', 'Original Specified Amount Units'),
        ('ORG_LTC_UNT_QTY', 'Original DBA Units'),
        ('ORG_LTC_VPU_AMT', 'Original DBA Value Per Unit'),
        ('PAY_UP_DT', 'Pay-Up Date'),
        ('PLN_BSE_SRE_CD', 'Base Code (part of plancode)'),
        ('PLN_DES_SER_CD', 'Plan Description Search Key'),
        ('POL_FRM_INP_IND', 'Input Form Number Flag'),
        ('POL_FRM_NBR', 'Policy Form Number'),
        ('PRD_AMT', 'Production Amount'),
        ('PRD_LIN_TYP_CD', 'Product Line Control Code'),
        ('PRD_PCT', 'Production Percent'),
        ('PRD_VAL_USE_CD', 'Production Value Use Code'),
        ('PRS_CD', 'Person Code'),
        ('PRS_SEQ_NBR', 'Person Sequence'),
        ('PTR_IN_SCL_IND', 'Point in Scale Flag'),
        ('REFRESH_OR_RNL_AGE', 'Refresh/Renewal Age'),
        ('RENEWABLE_PRM_CD', 'Renewable Premium Indicator'),
        ('RES_ITS_RT', 'Valuation Interest Rate'),
        ('RET_OF_PRM_CD', 'Return of Premium Code'),
        ('RET_PRM_UNT_AMT', 'Return Premium Per Unit'),
        ('RID_COI_BAN_RLE_CD', 'Death Benefit Rider'),
        ('RID_STA_CD', 'Rider Status Control Code'),
        ('RID_XPN_RLE_CD', 'Rider Expense Rule'),
        ('RMD_CLC_MTH_CD', 'RMD Calculation Method Code'),
        ('RMD_PAYOUT_CD', 'RMD Payout Code'),
        ('RPU_BNF_CD', 'Reduced Paid-Up (Nonforfeiture Rule)'),
        ('RT_BK_CD', 'Rate Book Code (part of plancode)'),
        ('SBQ_RNL_PER', 'Subsequent Renewal Period'),
        ('SBQ_RNL_STR_DUR', 'Subsequent Renewal Start Duration'),
        ('SUTB_IND', 'Suitability'),
        ('TAMRA_GDF_IND', 'TAMRA Grandfather Indicator'),
        ('TCH_POL_ID', 'Policy Number + Code (Primary Key)'),
        ('TRUE_AGE', 'True Age'),
        ('UNISEX_GUA_RT_CD', 'Unisex Guaranteed Rate Sex Code'),
        ('UNISEX_OVR_CD', 'Unisex Override Indicator'),
        ('UNISEX_SEX_CD', 'Unisex Sex Code'),
        ('UNISEX_SSR_CD', 'Unisex Subseries Code'),
        ('UNT_REQ_IND', 'Units Request Flag'),
        ('VAL_MTH_CD', 'Modification Valuation Method Code'),
        ('VAL_TBL_RFR_CD', 'Values Table Reference Code'),
        ('VAL_USE_CD', 'Value-Per-Unit Use Code'),
        ('DTH_BEN_ADJ_IND', ''),
        ('IAF_KEY_VERSION_CD', ''),
        ('PREMIUM_RESID_CD', ''),
        ('EFF_DT_OVERRIDE_CD', ''),
        ('PDF_KEY_EFF_DT', ''),
        ('PDF_KEY_VERSION_CD', ''),
    ],
    'TH_COV_PHA': [
        ('AN_PRD_ID', ''),
        ('CK_CMP_CD', 'Company Code (Primary Key)'),
        ('CK_SYS_CD', 'System Code (Primary Key)'),
        ('COV_PHA_NBR', 'Coverage Phase Control Code'),
        ('TCH_POL_ID', 'Policy Number + Code (Primary Key)'),
        ('COLA_INCR_IND', 'COLA Increase Indicator'),
    ],
}
